//! Request tracing middleware for the BPM Platform REST API.
//!
//! Implements API-09: assigns a UUID v4 trace_id to every request.
//! Propagates X-Trace-Id from the incoming request header if present
//! (any string value; no UUID validation is performed on incoming values).
//! Stores the trace_id in trace_context so all log entries and error
//! responses within the request carry the same value.
//!
//! This middleware MUST run FIRST — before auth, content-type, and all
//! other middleware — so that even authentication failures are traceable.
//!
//! Usage pattern (HTTP server integration layer):
//!   const result = try trace.extractOrGenerate(allocator, x_trace_id_header);
//!   defer allocator.free(result.trace_id);
//!   trace_context.set(result.trace_id);
//!   defer trace_context.clear();
//!   // ... invoke next middleware ...
//!   // HTTP server writes X-Trace-Id response header from trace_context.get()

const std = @import("std");
const builtin = @import("builtin");
const trace_context = @import("../trace_context.zig");

// ── Constants ─────────────────────────────────────────────────────────────────

/// Length of a UUID v4 string: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx (36 chars).
pub const UUID_V4_LEN: usize = 36;

/// Maximum accepted length for a propagated X-Trace-Id header value.
/// Prevents memory exhaustion from malicious callers (security constraint).
pub const MAX_TRACE_ID_LEN: usize = 256;

// ── Public types ──────────────────────────────────────────────────────────────

/// Result of extractOrGenerate().
pub const TraceIdResult = struct {
    /// The effective trace ID for this request.
    /// Either propagated from the X-Trace-Id request header
    /// or freshly generated.
    trace_id: []const u8,
    /// True if the trace ID was propagated from the caller.
    /// False if it was generated by the platform.
    propagated: bool,
};

// ── Error set ─────────────────────────────────────────────────────────────────

pub const TraceError = error{
    /// allocator.alloc failed while duplicating an incoming trace ID
    /// or allocating the UUID buffer.
    OutOfMemory,
};

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Fill buf with cryptographically secure random bytes.
/// Replaces std.crypto.random removed in Zig 0.16.
fn fillRandom(buf: []u8) void {
    switch (comptime builtin.os.tag) {
        .linux => _ = std.os.linux.getrandom(buf.ptr, buf.len, 0),
        .windows => {
            const adv = struct {
                extern "advapi32" fn SystemFunction036(pbBuffer: *anyopaque, cbBuffer: u32) u8;
            };
            _ = adv.SystemFunction036(@ptrCast(buf.ptr), @intCast(buf.len));
        },
        .macos, .ios, .tvos, .watchos, .visionos, .driverkit, .freebsd, .netbsd, .openbsd, .dragonfly => std.c.arc4random_buf(buf.ptr, buf.len),
        else => @compileError("fillRandom: unsupported OS — add a platform branch"),
    }
}

// ── Public functions ──────────────────────────────────────────────────────────

/// Extract the trace ID from the X-Trace-Id request header,
/// or generate a new UUID v4 if the header is absent or empty.
///
/// Rules:
///   - If x_trace_id_header is non-null and non-empty: propagate as-is.
///     Values longer than MAX_TRACE_ID_LEN are silently truncated.
///     No UUID validation is performed on the incoming value.
///   - Otherwise: generate a UUID v4 using std.crypto.random.
///
/// The returned slice is owned by the caller.
/// Caller must allocator.free(result.trace_id) when done.
pub fn extractOrGenerate(
    allocator: std.mem.Allocator,
    x_trace_id_header: ?[]const u8,
) TraceError!TraceIdResult {
    if (x_trace_id_header) |hdr| {
        if (hdr.len > 0) {
            // Propagate incoming trace ID (cap to MAX_TRACE_ID_LEN for safety).
            const len = @min(hdr.len, MAX_TRACE_ID_LEN);
            const copy = try allocator.alloc(u8, len);
            @memcpy(copy, hdr[0..len]);
            return .{ .trace_id = copy, .propagated = true };
        }
    }
    // Generate a fresh UUID v4.
    var buf: [UUID_V4_LEN]u8 = undefined;
    generateUuidV4(&buf);
    const copy = try allocator.alloc(u8, UUID_V4_LEN);
    @memcpy(copy, &buf);
    return .{ .trace_id = copy, .propagated = false };
}

/// Generate a UUID v4 string (36 chars) into the provided buffer.
/// No allocation.  buf must be exactly UUID_V4_LEN bytes.
///
/// Randomness source: std.crypto.random.bytes() (CSPRNG).
/// Version bits  : raw[6] = (raw[6] & 0x0f) | 0x40
/// Variant bits  : raw[8] = (raw[8] & 0x3f) | 0x80
///
/// Output format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
pub fn generateUuidV4(buf: *[UUID_V4_LEN]u8) void {
    var raw: [16]u8 = undefined;
    fillRandom(&raw);

    // Set version 4 bits.
    raw[6] = (raw[6] & 0x0f) | 0x40;
    // Set variant bits (RFC 4122).
    raw[8] = (raw[8] & 0x3f) | 0x80;

    // Encode as xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    // Groups by byte count: [4, 2, 2, 2, 6]
    const hex = "0123456789abcdef";
    const group_byte_counts = [_]usize{ 4, 2, 2, 2, 6 };
    var buf_pos: usize = 0;
    var raw_pos: usize = 0;
    for (group_byte_counts, 0..) |n_bytes, gi| {
        if (gi > 0) {
            buf[buf_pos] = '-';
            buf_pos += 1;
        }
        var b: usize = 0;
        while (b < n_bytes) : (b += 1) {
            buf[buf_pos] = hex[raw[raw_pos] >> 4];
            buf[buf_pos + 1] = hex[raw[raw_pos] & 0x0f];
            buf_pos += 2;
            raw_pos += 1;
        }
    }
}

// ── Embedded unit tests ───────────────────────────────────────────────────────

const testing = std.testing;

test "generateUuidV4: output is 36 bytes" {
    var buf: [UUID_V4_LEN]u8 = undefined;
    generateUuidV4(&buf);
    try testing.expectEqual(@as(usize, 36), buf.len);
}

test "generateUuidV4: dashes at positions 8, 13, 18, 23" {
    var buf: [UUID_V4_LEN]u8 = undefined;
    generateUuidV4(&buf);
    try testing.expectEqual('-', buf[8]);
    try testing.expectEqual('-', buf[13]);
    try testing.expectEqual('-', buf[18]);
    try testing.expectEqual('-', buf[23]);
}

test "generateUuidV4: version nibble is '4'" {
    var buf: [UUID_V4_LEN]u8 = undefined;
    generateUuidV4(&buf);
    // Character at position 14 is the version nibble (must be '4').
    try testing.expectEqual('4', buf[14]);
}

test "generateUuidV4: variant nibble is '8', '9', 'a', or 'b'" {
    var buf: [UUID_V4_LEN]u8 = undefined;
    generateUuidV4(&buf);
    // Character at position 19 is the high nibble of raw[8] after variant masking.
    const variant_char = buf[19];
    const valid = variant_char == '8' or variant_char == '9' or
        variant_char == 'a' or variant_char == 'b';
    try testing.expect(valid);
}

test "extractOrGenerate: null header generates a UUID" {
    const alloc = testing.allocator;
    const result = try extractOrGenerate(alloc, null);
    defer alloc.free(result.trace_id);

    try testing.expectEqual(false, result.propagated);
    try testing.expectEqual(@as(usize, UUID_V4_LEN), result.trace_id.len);
    // Check dash positions.
    try testing.expectEqual('-', result.trace_id[8]);
    try testing.expectEqual('-', result.trace_id[13]);
    try testing.expectEqual('-', result.trace_id[18]);
    try testing.expectEqual('-', result.trace_id[23]);
}

test "extractOrGenerate: empty header generates a UUID" {
    const alloc = testing.allocator;
    const result = try extractOrGenerate(alloc, "");
    defer alloc.free(result.trace_id);

    try testing.expectEqual(false, result.propagated);
    try testing.expectEqual(@as(usize, UUID_V4_LEN), result.trace_id.len);
}

test "extractOrGenerate: non-empty header propagates as-is" {
    const alloc = testing.allocator;
    const incoming = "my-trace-id-12345";
    const result = try extractOrGenerate(alloc, incoming);
    defer alloc.free(result.trace_id);

    try testing.expectEqual(true, result.propagated);
    try testing.expectEqualStrings(incoming, result.trace_id);
}

test "extractOrGenerate: non-UUID header propagated without validation" {
    const alloc = testing.allocator;
    const incoming = "not-a-uuid";
    const result = try extractOrGenerate(alloc, incoming);
    defer alloc.free(result.trace_id);

    try testing.expectEqual(true, result.propagated);
    try testing.expectEqualStrings("not-a-uuid", result.trace_id);
}

test "extractOrGenerate: header longer than MAX_TRACE_ID_LEN is truncated" {
    const alloc = testing.allocator;
    const long_id = "x"**(MAX_TRACE_ID_LEN + 10);
    const result = try extractOrGenerate(alloc, long_id);
    defer alloc.free(result.trace_id);

    try testing.expectEqual(true, result.propagated);
    try testing.expectEqual(@as(usize, MAX_TRACE_ID_LEN), result.trace_id.len);
}
