-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 084_iss104_artifact_hash.sql
-- Requirements: ISS-104
--
-- Add instances.artifact_hash TEXT NULL column to store the content hash of the
-- promoted artifact that the instance was started from. This enables reproducibility
-- queries (instance → artifact) without reading the definition registry again.
-- The change is additive: existing instances are unaffected (NULL). No index is
-- created (hash is not used as a lookup key in this migration).

ALTER TABLE instances
    ADD COLUMN IF NOT EXISTS artifact_hash TEXT;
