-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 086_iss107_tenant_storage_mode.sql
-- Requirements: ISS-107
--
-- Add a storage_mode flag to the public.tenant table so each tenant has exactly
-- one authoritative storage path during SPT (schema-per-tenant) coexistence.
-- Valid values: LEGACY_RLS (existing RLS-based path) and SCHEMA (new schema-per-tenant path).
-- Existing tenants default to LEGACY_RLS; newly provisioned tenants default to SCHEMA
-- (set by the Zig-side provisionTenantSchema() function in src/db/provisioning.zig).

ALTER TABLE tenant
    ADD COLUMN IF NOT EXISTS storage_mode text NOT NULL DEFAULT 'LEGACY_RLS' CHECK (storage_mode IN ('LEGACY_RLS','SCHEMA'));

CREATE INDEX IF NOT EXISTS idx_tenant_storage_mode ON tenant (storage_mode);
