-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 096_promotion_reviews.sql
-- Requirements: PRM-04
--
-- scope: tenant_only
--
-- INV-1 fix (WF-02 Step 2a rework 1): this table is tenant business data and
-- must live ONLY in per-tenant schemas (tenant_default, tenant_<uuid>), never
-- in public. The `tenant_id` column is the owning (target) tenant. Marking the
-- migration tenant_only stops the public pass from creating a shared public
-- copy; any historical public shadow is dropped by GBL-143.
--
-- Persist promotion approvals in a promotion_reviews table. The table is the
-- central state machine for the promotion pipeline: records who requested a
-- promotion, what plan was approved, who approved it, and whether it has been
-- applied/rejected/failed/superseded. Status is CHECK-constrained to exactly
-- six values. Partial unique index enforces at most one live review per
-- (tenant_id, plan_digest). Extends PRM-01 (plan submission) and PRM-03
-- (plan digest storage), and is read by PRM-05 (approval gate), PRM-06/07
-- (assertion re-run), PRM-08 (rollback), and PRM-09 (solution pack).

CREATE TABLE IF NOT EXISTS promotion_reviews (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id uuid NOT NULL,
    plan_digest text NOT NULL,
    def_type text NOT NULL,
    def_id text NOT NULL,
    serialised_plan text NOT NULL,
    status text NOT NULL DEFAULT 'pending_review',
    requested_by uuid NOT NULL,
    approved_by uuid,
    approved_at timestamptz,
    superseded_by uuid,
    row_version integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chk_promotion_reviews_status CHECK (status IN ('pending_review','approved','rejected','applied','failed','superseded'))
);

CREATE INDEX IF NOT EXISTS idx_promotion_reviews_tenant_id ON promotion_reviews (tenant_id);

CREATE INDEX IF NOT EXISTS idx_promotion_reviews_status ON promotion_reviews (status);

CREATE INDEX IF NOT EXISTS idx_promotion_reviews_requested_by ON promotion_reviews (requested_by);

CREATE UNIQUE INDEX IF NOT EXISTS promotion_reviews_plan_digest_active_uniq ON promotion_reviews (tenant_id, plan_digest) WHERE status IN ('pending_review', 'approved');

CREATE INDEX IF NOT EXISTS idx_promotion_reviews_tenant_status ON promotion_reviews (tenant_id, status) WHERE status IN ('applied', 'superseded');
