-- scope: public
-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1144_platform_migrations_control_table.sql
-- Requirements: MIG-01
--
-- Introduce platform.platform_migrations, the single cross-tenant control
-- table recording per-(migration_id, tenant_id) migration status
-- (pending/done/failed). This is the control-row half of the transactional
-- commit-with-DDL semantics MIG-02 defines and the fanout loop MIG-03 drives;
-- it replaces reliance on the per-schema public.schema_migrations table as
-- the only record of platform migration state. See
-- src/design/mig-02-mig-03-platform-migration-fanout.md for the fanout logic
-- that writes and reads this table. This migration only creates the schema
-- and table/index shape; it contains no fanout logic (that is Type E, not
-- Type C, per templates/lego-catalog.md's selection rules).

-- CUSTOM: the codegen tool has no schema-preamble field (see the
-- IMPLEMENTER NOTE at the top of templates/specs/mig-01-platform-migrations-control-table.migration.yaml).
-- platform.platform_migrations is a cross-tenant control table whose
-- canonical home is a dedicated `platform` schema, never `public` and never
-- any tenant schema, so it is created and schema-qualified explicitly here
-- rather than relying on search_path resolution (the documented, deliberate
-- exception to the "unqualified table names" convention).
CREATE SCHEMA IF NOT EXISTS platform;

CREATE TABLE IF NOT EXISTS platform.platform_migrations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    migration_id text NOT NULL,
    tenant_id uuid NOT NULL,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'done', 'failed')),
    error_msg text,
    completed_at timestamptz,
    run_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT platform_migrations_migration_tenant_uq UNIQUE (migration_id, tenant_id)
);

CREATE INDEX IF NOT EXISTS platform_migrations_resume_idx ON platform.platform_migrations (migration_id, status) WHERE status IN ('pending', 'failed');
-- END CUSTOM
