-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1145_ord01_plat_effect_completion.sql
-- Requirements: ORD-01, ORD-02, ORD-04
--
-- Creates plat_effect_completion, the table BPM Consumers poll to claim and apply
-- correlated effect completions in order. One row per completion; status starts
-- PENDING, becomes APPLIED (ORD-03, a later batch) or DEAD (ORD-03's gap sweeper,
-- a later batch). This batch (ORD-01/02/04) only claims and observes rows via
-- FOR UPDATE SKIP LOCKED plus a per-correlation advisory lock; it never transitions
-- status away from PENDING — see the Type E design's "State transitions" section.
--
-- Columns follow docs/processes/system/effect-reentry-ordering.md's Inputs table
-- exactly: completion_id (PK), correlation_id, sequence_no, status, payload,
-- received_at. (correlation_id, sequence_no) is UNIQUE so a retried Effects Worker
-- insert is absorbed by ON CONFLICT DO NOTHING (process doc step 1 / Business Rules
-- "Duplicate completions"), and the claim index matches the ORD-01 claim query's
-- exact WHERE/ORDER BY shape (status='PENDING' ORDER BY correlation_id, sequence_no).

CREATE TABLE IF NOT EXISTS plat_effect_completion (
    completion_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    correlation_id text NOT NULL,
    sequence_no bigint NOT NULL,
    status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPLIED','DEAD')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    received_at timestamptz NOT NULL DEFAULT now(),
    applied_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT plat_effect_completion_correlation_seq_uq UNIQUE (correlation_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_plat_effect_completion_claim ON plat_effect_completion (correlation_id, sequence_no) WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_plat_effect_completion_correlation ON plat_effect_completion (correlation_id, sequence_no);
