-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1146_ord04_plat_correlation_cursor.sql
-- Requirements: ORD-04, ORD-02
--
-- Creates plat_correlation_cursor, one row per correlation_id carrying the
-- highest sequence_no successfully applied (applied_seq). ORD-02's execute guard
-- reads this value while holding the per-correlation advisory lock (process doc
-- step 4); ORD-04's lag metric is max(sequence_no) [from plat_effect_completion]
-- minus applied_seq per correlation_id, read directly off this table with no
-- separate aggregate table needed. ORD-03 (a later batch) owns the conditional
-- UPDATE ... WHERE applied_seq = $2 - 1 cursor-advance statement and the
-- MissingCursorRow recovery (insert at applied_seq=0) — this migration only
-- creates the table shape both ORD-02 (read-only, this batch) and ORD-03
-- (read-write, later batch) need, per the Type E design's explicit statement
-- that ORD-03's design must not need a schema change here.

CREATE TABLE IF NOT EXISTS plat_correlation_cursor (
    correlation_id text PRIMARY KEY,
    applied_seq bigint NOT NULL DEFAULT 0 CHECK (applied_seq >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plat_correlation_cursor_updated ON plat_correlation_cursor (updated_at);
