-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1149_par03_retention_class.sql
-- Requirements: PAR-03
--
-- Adds retention_class to event_type_registry so RetentionClassForbidden
-- (PAR-03 AC1) has a concrete column to validate against. events_ephemeral
-- (the third RANGE-partitioned parent PAR-03 also requires, confined to
-- delete-class event types per ADP-11's protected-family prohibition) is
-- hand-written in the same migration file per the IMPLEMENTER NOTE above —
-- this YAML's `tables:` block covers only the codegen-clean ALTER.
--
-- REWORK 1 (CODE-DESIGN-VALIDATOR BLOCKER 1): PAR-03 AC1 requires configuring
-- retention_class = 'delete' for a protected-family event type ({INSTANCE_*,
-- TASK_*, GATEWAY_*, EXECUTION_*}) to be rejected with RetentionClassForbidden.
-- This migration now adds a SECOND check constraint (chk_retention_class_protected_family,
-- below) as the DB-level backstop for that rule, alongside the app-level guard
-- added to Registry.registerType()/validateRegisterParams in the same commit
-- (src/event_store/registry.zig) — see
-- src/design/par-03-partition-scoped-retention.md's "RetentionClassForbidden
-- guard" section for the full call-site, error-taxonomy, and access-control
-- spec (this is user-input-configured, platform-admin-gated data).

-- event_type_registry is a PER_TENANT table (docs/anti-patterns.md's
-- dual-schema classification; canonical home tenant_default) —
-- GBL-112_tnt01_drop_legacy_public_business_tables.sql (order ~1112, runs
-- before this migration's ~1149) permanently DROP TABLE ... CASCADE'd
-- public.event_type_registry. Confirmed live against bpm_dev: an unguarded
-- ALTER TABLE here fails migration-time with C42P01 "relation
-- event_type_registry does not exist" in the public pass, the exact same
-- class of defect PAR-01's Migration 3 (webhook_deliveries, above/earlier in
-- the batch) already hit and was guarded for. Guard the whole
-- event_type_registry block the same way.
DO $$
BEGIN
    IF to_regclass('event_type_registry') IS NULL THEN
        RAISE NOTICE 'PAR-03: event_type_registry absent in this schema pass — skipping retention_class column/constraints (per-tenant table, see comment above).';
        RETURN;
    END IF;

    ALTER TABLE event_type_registry
        ADD COLUMN IF NOT EXISTS retention_class text NOT NULL DEFAULT 'archive_queryable';

    -- CUSTOM: value-domain CHECK + PAR-03 AC1's DB-level protected-family
    -- backstop. Guarded with a pg_constraint existence check for idempotency
    -- (ALTER TABLE ... ADD CONSTRAINT has no IF NOT EXISTS form).
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'event_type_registry' AND c.conname = 'chk_retention_class'
    ) THEN
        ALTER TABLE event_type_registry ADD CONSTRAINT chk_retention_class
            CHECK (retention_class IN ('retain_forever', 'archive_queryable', 'delete'));
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'event_type_registry' AND c.conname = 'chk_retention_class_protected_family'
    ) THEN
        ALTER TABLE event_type_registry ADD CONSTRAINT chk_retention_class_protected_family
            CHECK (
                retention_class <> 'delete'
                OR split_part(name, '_', 1) NOT IN ('INSTANCE', 'TASK', 'GATEWAY', 'EXECUTION')
            );
    END IF;
END $$;

-- CUSTOM: events_ephemeral — hand-written (codegen has no PARTITION BY /
-- composite-PK support; see the IMPLEMENTER NOTE in
-- templates/specs/par-03-retention-class.migration.yaml and PAR-01's
-- Migration 1 + Migration 4 pattern, reused verbatim here). Guarded the same
-- way PAR-01's Migration 1 guards events/events_archive: skip the whole
-- rebuild if events_ephemeral is already partitioned (idempotent re-run).
--
-- Every existence check below is explicitly scoped to current_schema() —
-- see migrations/1147_par01_events_partitioning.sql's header comment for the
-- full account of why: this migration re-runs once per schema pass, and a
-- bare to_regclass()/unqualified pg_class or pg_inherits lookup during a
-- tenant pass can resolve through search_path to public's (or an earlier
-- tenant's) already-created same-named partition, silently skipping
-- CREATE/ATTACH for the CURRENT schema. Confirmed live as the root cause of
-- tenant_default.events ending up with zero attached partitions after a
-- full migrate run; the identical pattern here would produce the identical
-- defect for events_ephemeral.
DO $$
DECLARE
    v_is_partitioned BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM pg_partitioned_table pt
        JOIN pg_class c ON c.oid = pt.partrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'events_ephemeral' AND n.nspname = current_schema()
    ) INTO v_is_partitioned;

    IF NOT v_is_partitioned THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = 'events_ephemeral' AND n.nspname = current_schema()
        ) THEN
            -- created_at DEFAULT NOW() added (the design doc's own sketch
            -- omitted it, matching events_archive's row-preserving-move
            -- shape) — but events_ephemeral, unlike events_archive, is a
            -- direct Store.append() INSERT target (PAR-03's append-time
            -- routing), and Store.append()'s shared events/events_ephemeral
            -- INSERT statement never supplies created_at explicitly (it
            -- relies on the column default, exactly as events' own
            -- created_at DEFAULT NOW() already does) — confirmed live: a
            -- missing default here makes every delete-class append fail
            -- with "no partition of relation events_ephemeral found for
            -- row ... created_at = null" the moment PAR-03's routing sends
            -- an event here.
            CREATE TABLE events_ephemeral (
                event_id          UUID            NOT NULL,
                instance_id       UUID            NOT NULL,
                event_type        TEXT            NOT NULL,
                payload           JSONB           NOT NULL DEFAULT '{}',
                actor_id          UUID            NOT NULL,
                created_at        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                sequence_number   BIGINT          NOT NULL,
                idempotency_key   TEXT            NOT NULL,
                metadata          JSONB           NOT NULL DEFAULT '{}',
                global_seq        BIGINT          NOT NULL,
                tenant_id         UUID            NOT NULL,
                PRIMARY KEY (event_id, created_at)
            ) PARTITION BY RANGE (created_at);

            CREATE INDEX idx_events_ephemeral_instance ON events_ephemeral (instance_id, sequence_number);
            CREATE INDEX idx_events_ephemeral_type ON events_ephemeral (event_type);
        END IF;
    END IF;
END $$;

-- CUSTOM: initial partition seed for events_ephemeral — same 3-month
-- (current + lead_months=2) loop as PAR-01's Migration 4, retargeted.
DO $$
DECLARE
    v_month_start DATE := date_trunc('month', now())::date;
    v_offset INT;
    v_partition_name TEXT;
    v_range_start TIMESTAMPTZ;
    v_range_end TIMESTAMPTZ;
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_partitioned_table pt
        JOIN pg_class c ON c.oid = pt.partrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relname = 'events_ephemeral' AND n.nspname = current_schema()
    ) THEN
        FOR v_offset IN 0..2 LOOP
            v_range_start := (v_month_start + (v_offset || ' months')::interval);
            v_range_end := (v_month_start + ((v_offset + 1) || ' months')::interval);
            v_partition_name := 'events_ephemeral_' || to_char(v_range_start, 'YYYY_MM');

            IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relname = v_partition_name AND n.nspname = current_schema()
            ) THEN
                EXECUTE format(
                    'CREATE TABLE %I (LIKE events_ephemeral INCLUDING DEFAULTS, '
                    'CHECK (tenant_id IS NOT NULL), '
                    'CHECK (created_at >= %L AND created_at < %L))',
                    v_partition_name, v_range_start, v_range_end
                );
            END IF;
            IF NOT EXISTS (
                SELECT 1 FROM pg_inherits i
                JOIN pg_class child ON child.oid = i.inhrelid
                JOIN pg_namespace n ON n.oid = child.relnamespace
                WHERE child.relname = v_partition_name AND n.nspname = current_schema()
            ) THEN
                EXECUTE format(
                    'ALTER TABLE events_ephemeral ATTACH PARTITION %I FOR VALUES FROM (%L) TO (%L)',
                    v_partition_name, v_range_start, v_range_end
                );
            END IF;
        END LOOP;
    END IF;
END $$;

-- CUSTOM: plat_partition_catalog rows for the events_ephemeral seed above,
-- so PAR-02's creation loop and PAR-03's own retention logic see these
-- partitions as already ATTACHED and do not attempt to recreate them.
-- plat_partition_catalog is itself a per-schema (per-tenant) table — the
-- plain unqualified INSERT below resolves via normal search_path DML
-- resolution to the CURRENT schema's own copy (not a catalog-introspection
-- lookup), so this part does not need current_schema() scoping; only the
-- to_regclass() existence check does, for the same reason as every check
-- above.
DO $$
DECLARE
    v_month_start DATE := date_trunc('month', now())::date;
    v_offset INT;
    v_partition_name TEXT;
    v_range_start TIMESTAMPTZ;
    v_range_end TIMESTAMPTZ;
BEGIN
    FOR v_offset IN 0..2 LOOP
        v_range_start := (v_month_start + (v_offset || ' months')::interval);
        v_range_end := (v_month_start + ((v_offset + 1) || ' months')::interval);
        v_partition_name := 'events_ephemeral_' || to_char(v_range_start, 'YYYY_MM');

        IF EXISTS (
            SELECT 1 FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = v_partition_name AND n.nspname = current_schema()
        ) THEN
            INSERT INTO plat_partition_catalog (table_name, parent_table, range_start, range_end, state)
            VALUES (v_partition_name, 'events_ephemeral', v_range_start, v_range_end, 'ATTACHED')
            ON CONFLICT (table_name) DO NOTHING;
        END IF;
    END LOOP;
END $$;

-- CUSTOM: plat_partition_catalog rows for PAR-01's events/events_archive
-- initial seed (migration 1147). plat_partition_catalog does not exist until
-- THIS migration's dependency (1148_par02_partition_catalog.sql) has run, so
-- it cannot be seeded from 1147 itself — done here instead, the first
-- migration in sequence where the table exists. Idempotent (ON CONFLICT DO
-- NOTHING on table_name's unique constraint).
DO $$
DECLARE
    v_month_start DATE := date_trunc('month', now())::date;
    v_offset INT;
    v_partition_name TEXT;
    v_range_start TIMESTAMPTZ;
    v_range_end TIMESTAMPTZ;
BEGIN
    FOR v_offset IN 0..2 LOOP
        v_range_start := (v_month_start + (v_offset || ' months')::interval);
        v_range_end := (v_month_start + ((v_offset + 1) || ' months')::interval);

        v_partition_name := 'events_' || to_char(v_range_start, 'YYYY_MM');
        IF EXISTS (
            SELECT 1 FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = v_partition_name AND n.nspname = current_schema()
        ) THEN
            INSERT INTO plat_partition_catalog (table_name, parent_table, range_start, range_end, state)
            VALUES (v_partition_name, 'events', v_range_start, v_range_end, 'ATTACHED')
            ON CONFLICT (table_name) DO NOTHING;
        END IF;

        v_partition_name := 'events_archive_' || to_char(v_range_start, 'YYYY_MM');
        IF EXISTS (
            SELECT 1 FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relname = v_partition_name AND n.nspname = current_schema()
        ) THEN
            INSERT INTO plat_partition_catalog (table_name, parent_table, range_start, range_end, state)
            VALUES (v_partition_name, 'events_archive', v_range_start, v_range_end, 'ATTACHED')
            ON CONFLICT (table_name) DO NOTHING;
        END IF;
    END LOOP;
END $$;
