-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1150_par06_instance_projections_event_window.sql
-- Requirements: PAR-06
--
-- Add two nullable TIMESTAMPTZ columns to instance_projections — first_event_at and
-- last_event_at — that bound every instance-reconstruction query by created_at so
-- PAR-01's partition pruning actually applies to reads keyed by instance_id (which
-- carries no pruning information on its own). Both columns are maintained by
-- Store.append() in the SAME transaction as every event insert (see the companion
-- Type E design's Public interface section for the exact UPDATE statement — this is
-- an application-code change, not expressible in this migration YAML). Left nullable
-- deliberately: a NULL pair on an existing instance triggers the design's
-- ReconstructionWindowMissing self-healing repair path rather than a migration-time
-- backfill, so this migration performs no data backfill of its own.

-- CUSTOM: instance_projections is a PER_TENANT table (docs/anti-patterns.md's
-- dual-schema classification; canonical home tenant_default) —
-- GBL-135_iss0185_drop_per_tenant_shadows.sql permanently DROP TABLE'd
-- public.instance_projections's stray shadow (see that file's own header:
-- "FK chains from tables like users / groups / roles / events /
-- instance_projections all live in tenant_default"). An unguarded ALTER TABLE
-- here fails migration-time with C42P01 "relation instance_projections does
-- not exist" in the public pass — the exact same class of defect PAR-01's
-- Migration 3 (webhook_deliveries) and PAR-03's event_type_registry ALTER
-- were already guarded for (see migrations/1147_par01_events_partitioning.sql
-- and migrations/1149_par03_retention_class.sql). Guard the whole block the
-- same way rather than emitting the codegen'd ALTER unguarded at top level.
DO $$
BEGIN
    IF to_regclass('instance_projections') IS NULL THEN
        RAISE NOTICE 'PAR-06: instance_projections absent in this schema pass — skipping event-window columns/index (per-tenant table, see comment above).';
        RETURN;
    END IF;

    ALTER TABLE instance_projections
        ADD COLUMN IF NOT EXISTS first_event_at timestamptz,
        ADD COLUMN IF NOT EXISTS last_event_at timestamptz;

    CREATE INDEX IF NOT EXISTS idx_instance_projections_event_window ON instance_projections (instance_id, first_event_at, last_event_at);
END $$;
