-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1153_iss0686_archived_state.sql
-- Requirements: PAR-05, PAR-03
--
-- Extends the plat_partition_catalog.state CHECK constraint to include 'ARCHIVED',
-- a new terminal state written by archiveLegacyTable() after events_legacy is
-- renamed to events_legacy_archived. Without this migration the catalog UPDATE
-- at the end of archiveLegacyTable() fails with a constraint violation.

ALTER TABLE plat_partition_catalog
    DROP CONSTRAINT IF EXISTS plat_partition_catalog_state_check;

ALTER TABLE plat_partition_catalog
    ADD CONSTRAINT plat_partition_catalog_state_check CHECK (state IN ('ATTACHED', 'DETACHED', 'ORPHAN_PARTITION', 'DROPPED', 'ARCHIVED'));
