-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1163_ddl04_plat_migration_state.sql
-- Requirements: DDL-04
--
-- Creates plat_migration_state, one row per (migration_id, tenant_schema, phase)
-- recording the execution state and per-batch backfill progress of the three-phase
-- DDL generator (DDL-03's expand/backfill/constrain). The backfill loop of DDL-04
-- (src/platform/backfill.zig) writes rows_updated_total, rows_remaining,
-- last_batch_rows, last_batch_ms and stall_count on the SAME connection/transaction
-- as each batch commit, so progress is durable with the batch (DDL-04 AC6) and an
-- interrupted run can be resumed against the same `c IS NULL` predicate (DDL-04 AC1)
-- via the partial resume index. status transitions pending -> running -> applied |
-- failed; backfill_batch_size is the per-tenant live value the adaptive halving policy
-- (DDL-04 AC4, floor 500 / upper bound 50000) rewrites.

CREATE TABLE IF NOT EXISTS plat_migration_state (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    migration_id text NOT NULL,
    tenant_schema text NOT NULL,
    phase text NOT NULL CHECK (phase IN ('expand','backfill','constrain')),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','running','applied','failed')),
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    backfill_batch_size integer NOT NULL DEFAULT 5000 CHECK (backfill_batch_size BETWEEN 500 AND 50000),
    rows_updated_total bigint NOT NULL DEFAULT 0 CHECK (rows_updated_total >= 0),
    rows_remaining bigint NOT NULL DEFAULT 0 CHECK (rows_remaining >= 0),
    last_batch_rows bigint NOT NULL DEFAULT 0 CHECK (last_batch_rows >= 0),
    last_batch_ms bigint NOT NULL DEFAULT 0 CHECK (last_batch_ms >= 0),
    stall_count integer NOT NULL DEFAULT 0 CHECK (stall_count >= 0),
    last_error text,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT plat_migration_state_migration_tenant_phase_uq UNIQUE (migration_id, tenant_schema, phase)
);

CREATE INDEX IF NOT EXISTS idx_plat_migration_state_resume ON plat_migration_state (migration_id, status) WHERE status IN ('pending','running');

CREATE INDEX IF NOT EXISTS idx_plat_migration_state_tenant_phase ON plat_migration_state (tenant_schema, phase);
