-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1164_obp04_plat_outbox_gate.sql
-- Requirements: OBP-04
--
-- Creates plat_outbox_gate, one row per tenant schema recording the outbox ingress
-- gate state (open/closed), the last observed depth, the cap and the 80% low-water
-- hysteresis mark, the timestamp of the last transition, and the AC4/AC5 escalation
-- counters (refusal window + closed duration). The gate module (src/outbox/gate.zig)
-- persists every transition here in one transaction with the EXECUTION_OUTBOX_GATE_OPENED
-- event append (OBP-04 AC2); the row is keyed by tenant_schema so one tenant's depth
-- never refuses another tenant's ingress (OBP-04 AC6). low_water is writable so the
-- flapping recovery (OBP-04 AC3) can restore the 80% hysteresis mark in place.

CREATE TABLE IF NOT EXISTS plat_outbox_gate (
    tenant_schema text PRIMARY KEY,
    state text NOT NULL DEFAULT 'open' CHECK (state IN ('open','closed')),
    depth bigint NOT NULL DEFAULT 0 CHECK (depth >= 0),
    cap bigint NOT NULL CHECK (cap > 0),
    low_water bigint NOT NULL CHECK (low_water > 0 AND low_water < cap),
    last_transition_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    closed_duration_ms bigint NOT NULL DEFAULT 0 CHECK (closed_duration_ms >= 0),
    refusal_count_1m bigint NOT NULL DEFAULT 0 CHECK (refusal_count_1m >= 0),
    refusal_window_started_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plat_outbox_gate_closed ON plat_outbox_gate (state, closed_at) WHERE state = 'closed';

-- CUSTOM (OBP-04 AC2): seed EXECUTION_OUTBOX_GATE_OPENED in event_type_registry
-- so src/outbox/gate.zig::evaluateAndDecide's reopen append passes the ES-05
-- registry check. Mirrors migrations/1152_iss0670_platform_event_types_seed.sql:
-- guarded (event_type_registry is a PER_TENANT table, absent in the public pass),
-- idempotent ON CONFLICT (name, schema_version) DO NOTHING, retention_class =
-- 'retain_forever' (EXECUTION_* is a protected family per chk_retention_class_protected_family).
DO $$
BEGIN
    IF to_regclass('event_type_registry') IS NULL THEN
        RAISE NOTICE '1164: event_type_registry absent in this schema pass — skipping EXECUTION_OUTBOX_GATE_OPENED seed (per-tenant table).';
        RETURN;
    END IF;

    INSERT INTO event_type_registry (name, schema_version, json_schema, description, retention_class)
    VALUES
        (
            'EXECUTION_OUTBOX_GATE_OPENED', 1,
            '{"type":"object","required":["tenant_schema","closed_duration_ms"],"additionalProperties":false,"properties":{"tenant_schema":{"type":"string"},"closed_duration_ms":{"type":"integer"}}}'::jsonb,
            'OBP-04 AC2: outbox ingress gate reopened at the 80% low-water mark, carrying the closed duration',
            'retain_forever'
        )
    ON CONFLICT (name, schema_version) DO NOTHING;
END $$;
