-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1165_vld04_definition_semantic_verdict.sql
-- Requirements: VLD-04
--
-- Adds the semantic-validation verdict columns to process_definitions so the VLD-04
-- gate (src/validation/gate.zig) can record, per definition version, whether a clean
-- CEL compile produced semantically_valid = true, which compiler version produced the
-- verdict, when, and how many findings the last failed pass found. compiler_version is
-- nullable: a NULL means "never validated or the stored version is stale", which drives
-- VLD-04 AC3's re-verify-rather-than-trust rule. The columns are added with IF NOT
-- EXISTS so the migration is idempotent across the public and per-tenant schema passes
-- (process_definitions lives in every schema, per migration 004's PER_TENANT shadow
-- convention). This migration only adds the columns; the gating orchestration that reads
-- and writes them is Type E, per templates/lego-catalog.md's selection rules.

-- CUSTOM (BACKEND-DEV): process_definitions is a PER_TENANT table (absent in
-- the public schema pass, per GBL-112/GBL-142) and lives in every tenant
-- schema. The codegen boilerplate below runs the ALTER unconditionally, which
-- fails the public pass with "relation process_definitions does not exist".
-- Guard the ALTER the same way migrations/1149_par03_retention_class.sql
-- guards event_type_registry: skip the schema pass where the table is absent.
DO $$
BEGIN
    IF to_regclass('process_definitions') IS NULL THEN
        RAISE NOTICE '1165: process_definitions absent in this schema pass — skipping verdict columns (per-tenant table).';
        RETURN;
    END IF;

    ALTER TABLE process_definitions
        ADD COLUMN IF NOT EXISTS semantically_valid boolean NOT NULL DEFAULT false,
        ADD COLUMN IF NOT EXISTS compiler_version text,
        ADD COLUMN IF NOT EXISTS validated_at timestamptz,
        ADD COLUMN IF NOT EXISTS validation_finding_count integer NOT NULL DEFAULT 0 CHECK (validation_finding_count >= 0);
END $$;

-- CUSTOM (VLD-04 AC5, per the migration YAML's IMPLEMENTER NOTE): seed
-- DEFINITION_VALIDATED / DEFINITION_VALIDATION_FAILED in event_type_registry so
-- src/validation/gate.zig::persistVerdict's appends pass the ES-05 registry check.
-- Mirrors migrations/1152_iss0670_platform_event_types_seed.sql: guarded
-- (event_type_registry is a PER_TENANT table, absent in the public pass),
-- idempotent ON CONFLICT (name, schema_version) DO NOTHING, retention_class =
-- 'retain_forever' per PAR-03 AC1.
DO $$
BEGIN
    IF to_regclass('event_type_registry') IS NULL THEN
        RAISE NOTICE '1165: event_type_registry absent in this schema pass — skipping DEFINITION_* verdict-event seed (per-tenant table).';
        RETURN;
    END IF;

    INSERT INTO event_type_registry (name, schema_version, json_schema, description, retention_class)
    VALUES
        (
            'DEFINITION_VALIDATED', 1,
            '{"type":"object","required":["definition_id","compiler_version"],"additionalProperties":false,"properties":{"definition_id":{"type":"string"},"compiler_version":{"type":"string"}}}'::jsonb,
            'VLD-04 AC5: clean semantic-validation pass recorded on a definition version',
            'retain_forever'
        ),
        (
            'DEFINITION_VALIDATION_FAILED', 1,
            '{"type":"object","required":["definition_id","finding_count"],"additionalProperties":false,"properties":{"definition_id":{"type":"string"},"finding_count":{"type":"integer"}}}'::jsonb,
            'VLD-04 AC5: semantic-validation failure recorded on a definition version, carrying the finding count',
            'retain_forever'
        )
    ON CONFLICT (name, schema_version) DO NOTHING;
END $$;
