-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 1167_obp01_plat_outbox_gate_depth_ts.sql
-- Requirements: OBP-01, OBP-02
--
-- Adds depth_refreshed_at to plat_outbox_gate so the drainer can record when
-- it last refreshed the cached depth (OBP-01 AC3: a cached value older than 5 s
-- is treated as at-cap). Also seeds EXECUTION_INGRESS_REFUSED in
-- event_type_registry for OBP-02's async audit event append.

ALTER TABLE plat_outbox_gate
    ADD COLUMN IF NOT EXISTS depth_refreshed_at timestamptz NOT NULL DEFAULT now();
