-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- GBL-084_iss104_artifact_hash.sql
-- Requirements: ISS-104
--
-- Add instance_projections.artifact_hash TEXT NULL column to store the content hash of the
-- promoted artifact that the instance was started from. This enables reproducibility
-- queries (instance → artifact) without reading the definition registry again.
-- The change is additive: existing instances are unaffected (NULL). No index is
-- created (hash is not used as a lookup key in this migration).
--
-- Per-tenant migration: runs in each tenant schema and public schema.
-- Uses DO block with to_regclass() guard for idempotency, matching ISS-102 pattern.

DO $$
DECLARE
    v_table_oid OID;
BEGIN
    -- to_regclass() returns NULL if the table does not exist in the current
    -- search_path, making this migration a no-op when instance_projections
    -- does not exist (e.g., in public schema before any tenant creation).
    v_table_oid := to_regclass('instance_projections');
    IF v_table_oid IS NULL THEN
        -- instance_projections table does not exist in this schema; nothing to do.
        RETURN;
    END IF;

    -- Add artifact_hash column (idempotent).
    ALTER TABLE instance_projections
        ADD COLUMN IF NOT EXISTS artifact_hash TEXT;
END $$;
