-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 078_svc01_service_catalog_scope.sql
-- Requirements: SVC-01
--
-- Extend the service_catalog table with a `scope` column (global | tenant) and
-- a nullable `owner_tenant_id` FK referencing tenant(id) ON DELETE CASCADE.
-- A table-level CHECK constraint enforces that scope=global always has a NULL
-- owner_tenant_id and scope=tenant always has a non-NULL owner_tenant_id.
-- All pre-existing rows are set to scope='global', owner_tenant_id=NULL via the
-- column DEFAULT — no explicit UPDATE backfill is required.

ALTER TABLE service_catalog
    ADD COLUMN IF NOT EXISTS scope text NOT NULL DEFAULT 'global'
        CHECK (scope IN ('global', 'tenant')),
    ADD COLUMN IF NOT EXISTS owner_tenant_id uuid REFERENCES tenant(id) ON DELETE CASCADE;

-- CUSTOM: composite scope/owner consistency constraint (codegen cannot emit table-level constraints)
-- Enforces: scope='global' ↔ owner_tenant_id IS NULL; scope='tenant' ↔ owner_tenant_id IS NOT NULL
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_service_scope_owner'
          AND conrelid = 'service_catalog'::regclass
    ) THEN
        ALTER TABLE service_catalog
            ADD CONSTRAINT ck_service_scope_owner
            CHECK (
                (scope = 'global' AND owner_tenant_id IS NULL)
                OR (scope = 'tenant' AND owner_tenant_id IS NOT NULL)
            );
    END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_service_catalog_scope ON service_catalog (scope);

CREATE INDEX IF NOT EXISTS idx_service_catalog_owner_tenant ON service_catalog (owner_tenant_id);
