-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 080_env01_tenant_type_field.sql
-- Requirements: ENV-01
--
-- Extend public.tenant with two new columns:
--   - tenant_type TEXT NOT NULL DEFAULT 'production' CHECK IN ('production','test')
--   - production_tenant_id UUID NULL REFERENCES public.tenant(id) ON DELETE RESTRICT
-- A table-level CHECK constraint enforces the type/FK coherence invariant:
-- production tenants must have production_tenant_id IS NULL;
-- test tenants must have production_tenant_id IS NOT NULL.
-- All pre-existing rows are backfilled to tenant_type='production',
-- production_tenant_id=NULL via the column DEFAULT — no explicit UPDATE
-- is required for tenant_type. production_tenant_id defaults to NULL.
-- The existing POST /api/v1/tenants/onboard route (src/identity/onboarding.zig)
-- must accept the new fields and validate the constraint at the API level.
-- The existing GET /api/v1/admin/tenants route must expose both new columns.
-- PATCH /api/v1/tenants/:id must reject attempts to change tenant_type or
-- production_tenant_id with HTTP 422.

ALTER TABLE tenant
    ADD COLUMN IF NOT EXISTS tenant_type text NOT NULL DEFAULT 'production' CHECK (tenant_type IN ('production', 'test')),
    ADD COLUMN IF NOT EXISTS production_tenant_id uuid REFERENCES tenant(id) ON DELETE RESTRICT,
    ADD CONSTRAINT ck_tenant_type_fk_coherence CHECK ((tenant_type = 'production' AND production_tenant_id IS NULL) OR (tenant_type = 'test' AND production_tenant_id IS NOT NULL));

CREATE INDEX IF NOT EXISTS idx_tenant_production_tenant_id ON tenant (production_tenant_id);
