-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML.
-- 081_iss101_timers_failed_status.sql
-- Requirements: ISS-101
--
-- Extend the timers.status CHECK constraint to include 'failed', enabling the
-- scheduler (ISS-303) to move exhausted-retry timers to a terminal FAILED state.
-- Migration 015 constrained status to (pending, fired, cancelled); this migration
-- replaces that constraint with one that includes 'failed'.
-- The change is additive: existing rows are unaffected (their values remain valid).
-- The migration is idempotent: the DO $$ block drops the old constraint before
-- adding the new one, so the migration can safely be re-run.
--
-- NOTE ON PUBLIC SCHEMA: timers lives in per-tenant schemas only (public.timers was
-- dropped by GBL-073). The migration runner applies every non-GBL migration to both
-- public and all tenant schemas. When run against public (where timers does not exist),
-- this block is a no-op thanks to the to_regclass() guard. When run against a tenant
-- schema where timers exists, it replaces the constraint.

DO $$
DECLARE
    v_timers_oid OID;
BEGIN
    -- to_regclass() returns NULL if the table does not exist in the current search_path,
    -- avoiding the ERROR that '::regclass' would throw. This makes the migration a
    -- no-op when applied to the public schema (where timers no longer exists).
    v_timers_oid := to_regclass('timers');
    IF v_timers_oid IS NULL THEN
        -- timers table does not exist in this schema; nothing to do.
        RETURN;
    END IF;

    -- Drop the old constraint regardless of whether it carries 3 or 4 values.
    -- IF EXISTS prevents an error when the constraint was already removed.
    EXECUTE format('ALTER TABLE timers DROP CONSTRAINT IF EXISTS chk_timers_status_domain');

    -- Add the new constraint that includes 'failed'.
    EXECUTE format('ALTER TABLE timers ADD CONSTRAINT chk_timers_status_domain CHECK (lower(status) IN (''pending'', ''fired'', ''cancelled'', ''failed''))');
END
$$;
