// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/ddl04_plat_migration_state_test.zig
// Requirements: DDL-04
//
// Creates plat_migration_state, one row per (migration_id, tenant_schema, phase) recording
// the execution state and per-batch backfill progress of the three-phase DDL generator
// (DDL-03's expand/backfill/constrain). The backfill loop of DDL-04
// (src/platform/backfill.zig) writes rows_updated_total, rows_remaining, last_batch_rows,
// last_batch_ms and stall_count on the SAME connection/transaction as each batch commit, so
// progress is durable with the batch (DDL-04 AC6) and an interrupted run can be resumed
// against the same `c IS NULL` predicate (DDL-04 AC1) via the partial resume index. status
// transitions pending -> running -> applied | failed; backfill_batch_size is the per-tenant
// live value the adaptive halving policy (DDL-04 AC4, floor 500 / upper bound 50000)
// rewrites.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    migration_id_value: []u8,
    tenant_schema_value: []u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    // CUSTOM: realise per-test fixtures here (random strings + the seed running row).
    const migration_id_value = try allocator.dupe(u8, "ddl04-mig-00000000-0000-0000-0000-000000000001");
    errdefer allocator.free(migration_id_value);
    const tenant_schema_value = try allocator.dupe(u8, "ddl04-tenant-00000000-0000-0000-0000-000000000001");
    errdefer allocator.free(tenant_schema_value);

    // seed_running_backfill — an interrupted backfill left RUNNING at batch 40/100
    // (200000 updated, 50000 remaining). Tests 4 and 5 read it via
    // idx_plat_migration_state_resume.
    try conn.exec(
        \\INSERT INTO plat_migration_state
        \\  (migration_id, tenant_schema, phase, status, attempt_count,
        \\   backfill_batch_size, rows_updated_total, rows_remaining, last_batch_rows,
        \\   last_batch_ms, stall_count, started_at)
        \\VALUES
        \\  ($1, $2, 'backfill', 'running', 1, 5000, 200000, 50000, 5000, 1200, 0, now())
    ,
        &.{ migration_id_value, tenant_schema_value },
    );

    return Fixtures{
        .migration_id_value = migration_id_value,
        .tenant_schema_value = tenant_schema_value,
    };
}

fn freeFixtures(allocator: std.mem.Allocator, fx: Fixtures) void {
    allocator.free(fx.migration_id_value);
    allocator.free(fx.tenant_schema_value);
}

test "ddl04_plat_migration_state: unique_constraint_on_migration_tenant_phase" {
    // A second INSERT for the same (migration_id, tenant_schema, phase) violates the UNIQUE anchor used by the loop's progress upsert (DDL-04 AC6).
    // covers: DDL-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: start from a clean slate (remove the setup-seeded running row so
    // THIS test owns the first insert for the key).
    try h.conn.exec(
        "DELETE FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    try h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status) VALUES ($1, $2, 'backfill', 'running')",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    // CUSTOM: the SAVEPOINT must precede the failing (second) insert — after a
    // Postgres error the transaction is aborted and only ROLLBACK TO SAVEPOINT
    // can recover it.
    try h.conn.exec("SAVEPOINT before_dup", &.{});
    const result = h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status) VALUES ($1, $2, 'backfill', 'running')",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    // CUSTOM: assert the second INSERT returns a unique_violation (23505) on
    // plat_migration_state_migration_tenant_phase_uq, and that exactly one row
    // exists for (migration_id_value, tenant_schema_value, 'backfill').
    try std.testing.expectError(error.ServerError, result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_dup", &.{});

    var rows = try h.conn.query(std.testing.allocator,
        "SELECT count(*) FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value });
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("1", rows.rows[0][0] orelse "0");
}

test "ddl04_plat_migration_state: status_check_constraint_rejects_unknown_value" {
    // A status outside pending/running/applied/failed is rejected by the CHECK constraint.
    // covers: DDL-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: remove the setup-seeded row so the bogus-status insert is judged
    // on the status CHECK alone (not the (migration, tenant, phase) UNIQUE).
    try h.conn.exec(
        "DELETE FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    // CUSTOM: SAVEPOINT must precede the failing insert (Postgres aborts the
    // transaction on error; only ROLLBACK TO SAVEPOINT recovers it).
    try h.conn.exec("SAVEPOINT before_bogus", &.{});
    const result = h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status) VALUES ($1, $2, 'backfill', 'bogus')",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    // CUSTOM: assert error.CheckConstraintViolation (SQLSTATE 23514) and that
    // no row was inserted. pg.Conn surfaces server errors as error.ServerError;
    // the SQLSTATE is readable via lastSqlState() (see
    // tests/integration/platform_migrations_control_table_test.zig).
    try std.testing.expectError(error.ServerError, result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_bogus", &.{});

    var rows = try h.conn.query(std.testing.allocator,
        "SELECT count(*) FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value });
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("0", rows.rows[0][0] orelse "1");
}

test "ddl04_plat_migration_state: backfill_batch_size_check_bounds" {
    // backfill_batch_size is bounded 500..50000 (DDL-04 body upper bound 50000, AC4 floor 500); values outside are rejected by the CHECK constraint.
    // covers: DDL-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: remove the setup-seeded 'backfill' running row so the bounds
    // inserts are judged on the batch_size CHECK alone (not the UNIQUE key),
    // and the 500/50000 inserts can succeed.
    try h.conn.exec(
        "DELETE FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    // CUSTOM: SAVEPOINT must precede each failing insert.
    try h.conn.exec("SAVEPOINT before_100", &.{});
    const too_small = h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status, backfill_batch_size) VALUES ($1, $2, 'backfill', 'pending', 100)",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    // CUSTOM: assert too_small returns CheckConstraintViolation (23514). Repeat
    // with 60000 and assert the same; assert an insert with 500 and one with
    // 50000 both succeed.
    try std.testing.expectError(error.ServerError, too_small);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_100", &.{});

    try h.conn.exec("SAVEPOINT before_60000", &.{});
    const too_large = h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status, backfill_batch_size) VALUES ($1, $2, 'backfill', 'pending', 60000)",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );
    try std.testing.expectError(error.ServerError, too_large);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_60000", &.{});

    // CUSTOM: assert an insert with the floor 500 and one with the ceiling
    // 50000 both succeed. Distinct phases keep the two valid rows off the
    // (migration_id, tenant_schema, phase) UNIQUE anchor.
    try h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status, backfill_batch_size) VALUES ($1, $2, 'expand', 'pending', 500)",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );
    try h.conn.exec(
        "INSERT INTO plat_migration_state (migration_id, tenant_schema, phase, status, backfill_batch_size) VALUES ($1, $2, 'backfill', 'pending', 50000)",
        &.{ fx.migration_id_value, fx.tenant_schema_value },
    );

    var rows = try h.conn.query(std.testing.allocator,
        "SELECT count(*) FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND status = 'pending'",
        &.{ fx.migration_id_value, fx.tenant_schema_value });
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("2", rows.rows[0][0] orelse "0");
}

test "ddl04_plat_migration_state: resume_reads_persisted_progress" {
    // DDL-04 AC1 — an interrupted run's progress is queryable via the resume partial index and carries the cumulative counters a resumed loop reads to skip already-backfilled rows.
    // covers: DDL-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    var result = try h.conn.query(std.testing.allocator,
        "SELECT rows_updated_total, rows_remaining, backfill_batch_size, status FROM plat_migration_state WHERE migration_id = $1 AND status IN ('pending','running')",
        &.{fx.migration_id_value});
    defer result.deinit();

    // CUSTOM: assert result.rows.len == 1 (the seeded running row is found via
    // idx_plat_migration_state_resume), rows_updated_total == "200000",
    // rows_remaining == "50000", backfill_batch_size == "5000", status == "running".
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    const row = result.rows[0];
    try std.testing.expect(row.len >= 4);
    try std.testing.expectEqualStrings("200000", row[0] orelse "");
    try std.testing.expectEqualStrings("50000", row[1] orelse "");
    try std.testing.expectEqualStrings("5000", row[2] orelse "");
    try std.testing.expectEqualStrings("running", row[3] orelse "");
}

test "ddl04_plat_migration_state: progress_recording_updates_counters_in_place" {
    // DDL-04 AC6 — recordBatchProgress updates rows_updated_total/rows_remaining/ last_batch_rows/last_batch_ms on the existing row (no second row created), and a zero-remaining update leaves rows_remaining = 0 so the loop terminates.
    // covers: DDL-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "UPDATE plat_migration_state SET rows_updated_total = rows_updated_total + $3, rows_remaining = $4, last_batch_rows = $3, last_batch_ms = $5, updated_at = now() WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value, "5000", "45000", "900" },
    );

    // CUSTOM: assert exactly one row remains, rows_updated_total == "205000",
    // rows_remaining == "45000", last_batch_rows == "5000", last_batch_ms == "900".
    var rows = try h.conn.query(std.testing.allocator,
        "SELECT rows_updated_total, rows_remaining, last_batch_rows, last_batch_ms FROM plat_migration_state WHERE migration_id = $1 AND tenant_schema = $2 AND phase = 'backfill'",
        &.{ fx.migration_id_value, fx.tenant_schema_value });
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const row = rows.rows[0];
    try std.testing.expect(row.len >= 4);
    try std.testing.expectEqualStrings("205000", row[0] orelse "");
    try std.testing.expectEqualStrings("45000", row[1] orelse "");
    try std.testing.expectEqualStrings("5000", row[2] orelse "");
    try std.testing.expectEqualStrings("900", row[3] orelse "");
}
