// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/env01_tenant_type_field_test.zig
// Requirements: ENV-01
//
// Extend public.tenant with two new columns:   - tenant_type TEXT NOT NULL DEFAULT
// 'production' CHECK IN ('production','test')   - production_tenant_id UUID NULL REFERENCES
// public.tenant(id) ON DELETE RESTRICT A table-level CHECK constraint enforces the type/FK
// coherence invariant: production tenants must have production_tenant_id IS NULL; test
// tenants must have production_tenant_id IS NOT NULL. All pre-existing rows are backfilled
// to tenant_type='production', production_tenant_id=NULL via the column DEFAULT — no
// explicit UPDATE is required for tenant_type. production_tenant_id defaults to NULL. The
// existing POST /api/v1/tenants/onboard route (src/identity/onboarding.zig) must accept the
// new fields and validate the constraint at the API level. The existing GET
// /api/v1/admin/tenants route must expose both new columns. PATCH /api/v1/tenants/:id must
// reject attempts to change tenant_type or production_tenant_id with HTTP 422.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    prod_tenant_id: [16]u8,
    test_tenant_id: [16]u8,
};

// ISS-0137 / GH #439: this file is an UNFINISHED codegen scaffold. All nine of
// its `test` blocks below are `// CUSTOM:` placeholders containing zero
// assertions — the implementer never filled them in. It had not compiled since
// the Zig 0.16 upgrade (std.crypto.random removed, plus a `generated.uuid()`
// helper that exists nowhere) because it was wired into no build target, so
// nothing ever noticed.
//
// The real ENV-01 coverage lives in tests/integration/env01_test.zig (12 test
// blocks, 31 assertions) and is wired. This file is repaired to COMPILE rather
// than deleted or left unwired, so it stays visible to the wiring linter; the
// missing assertions are tracked as their own issue. Making it compile does not
// make it cover anything — that is the point of filing it rather than hiding it.
fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    _ = conn;
    _ = allocator;
    return Fixtures{
        .prod_tenant_id = helpers.randomUuidBytes(),
        .test_tenant_id = helpers.randomUuidBytes(),
    };
}

test "env01_tenant_type_field: backfill_existing_rows_are_production" {
    // Any tenant row present before migration has tenant_type='production' and production_tenant_id IS NULL.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // SELECT tenant_type, production_tenant_id FROM tenant WHERE id = fx.prod_tenant_id

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert tenant_type = 'production', production_tenant_id IS NULL for pre-existing row.
}

test "env01_tenant_type_field: production_tenant_insert_no_parent" {
    // A new production tenant can be inserted with no production_tenant_id.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // ISS-0137 / GH #439: was `generated.uuid()` — a helper that exists nowhere
    // in this repo. Only ever consumed by the commented-out INSERT below.
    const new_id = helpers.randomUuidBytes();
    _ = new_id;

    // INSERT INTO tenant (id, slug, display_name, status, idp_realm_id, tenant_type, production_tenant_id)
    // VALUES (new_id, 'prod-new', 'Prod New', 'ACTIVE', 'realm-x', 'production', NULL)

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert row inserted, tenant_type='production', production_tenant_id IS NULL.
}

test "env01_tenant_type_field: test_tenant_insert_with_valid_parent" {
    // A new test tenant can be inserted with a valid production_tenant_id.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // seed_prod_tenant already inserted

    // INSERT INTO tenant (..., tenant_type, production_tenant_id)
    // VALUES (fx.test_tenant_id, 'test-linked', ..., 'test', fx.prod_tenant_id)

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert row inserted, tenant_type='test', production_tenant_id = fx.prod_tenant_id.
}

test "env01_tenant_type_field: check_constraint_rejects_test_tenant_without_parent" {
    // A test tenant with production_tenant_id IS NULL violates ck_tenant_type_fk_coherence.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // INSERT INTO tenant (..., tenant_type, production_tenant_id)
    // VALUES (generated.uuid(), 'no-parent', ..., 'test', NULL)

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert database rejects with check constraint violation.
}

test "env01_tenant_type_field: check_constraint_rejects_production_tenant_with_parent" {
    // A production tenant with a non-null production_tenant_id violates ck_tenant_type_fk_coherence.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // seed_prod_tenant already inserted

    // INSERT INTO tenant (..., tenant_type, production_tenant_id)
    // VALUES (generated.uuid(), 'bad-prod', ..., 'production', fx.prod_tenant_id)

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert database rejects with check constraint violation.
}

test "env01_tenant_type_field: on_delete_restrict_blocks_deleting_parent_with_children" {
    // Deleting a production tenant that has test children is rejected (ON DELETE RESTRICT).
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // insert prod_tenant, insert test_tenant linked to prod_tenant

    // DELETE FROM tenant WHERE id = fx.prod_tenant_id

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert FK constraint violation; prod_tenant row still exists.
}

test "env01_tenant_type_field: admin_list_includes_new_fields" {
    // GET /api/v1/admin/tenants response includes tenant_type and production_tenant_id.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // seed both prod and test tenant rows

    // GET /api/v1/admin/tenants (platform-admin token)

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert each tenant entry has tenant_type field; test tenant has non-null production_tenant_id.
}

test "env01_tenant_type_field: patch_immutability_tenant_type" {
    // PATCH /api/v1/tenants/:id attempting to change tenant_type returns HTTP 422.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // seed prod_tenant row

    // PATCH /api/v1/tenants/fx.prod_tenant_id with body { "tenant_type": "test" }

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert HTTP 422 with message containing "tenant_type".
}

test "env01_tenant_type_field: patch_immutability_production_tenant_id" {
    // PATCH /api/v1/tenants/:id attempting to change production_tenant_id returns HTTP 422.
    // covers: ENV-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    _ = fx;

    // seed test_tenant row

    // PATCH /api/v1/tenants/fx.test_tenant_id with body { "production_tenant_id": "some-uuid" }

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert HTTP 422 with message containing "production_tenant_id".
}
