// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/iss0686_archived_state_test.zig
// Requirements: PAR-05, PAR-03
//
// Extends the plat_partition_catalog.state CHECK constraint to include 'ARCHIVED', a new
// terminal state written by archiveLegacyTable() after events_legacy is renamed to
// events_legacy_archived. Without this migration the catalog UPDATE at the end of
// archiveLegacyTable() fails with a constraint violation.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    _ = conn;
    _ = allocator;
    // CUSTOM: realise per-test fixtures here (UUIDs, random strings, seed SQL).
    return Fixtures{
    };
}

test "iss0686_archived_state: archived_state_accepted" {
    // A plat_partition_catalog row whose state is updated to 'ARCHIVED' is accepted by the extended CHECK constraint without a violation.
    // covers: PAR-05
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    try h.conn.exec(
        "INSERT INTO plat_partition_catalog " ++
        "  (table_name, parent_table, range_start, range_end, state) " ++
        "VALUES ('events_legacy_archived_test', 'events_legacy', " ++
        "        '1970-01-01'::timestamptz, NOW(), 'ATTACHED')",
        &.{},
    );

    try h.conn.exec(
        "UPDATE plat_partition_catalog SET state = 'ARCHIVED' " ++
        "WHERE table_name = 'events_legacy_archived_test'",
        &.{},
    );

    // CUSTOM: verify exactly one row has state='ARCHIVED'.
    var count_res = try h.conn.query(
        std.testing.allocator,
        "SELECT COUNT(*) FROM plat_partition_catalog WHERE table_name = 'events_legacy_archived_test' AND state = 'ARCHIVED'",
        &.{},
    );
    defer count_res.deinit();
    try std.testing.expect(count_res.rows.len > 0);
    try std.testing.expectEqualStrings("1", count_res.rows[0][0].?);
}
