// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/iss104_artifact_hash_test.zig
// Requirements: ISS-104
//
// Add instances.artifact_hash TEXT NULL column to store the content hash of the promoted
// artifact that the instance was started from. This enables reproducibility queries
// (instance → artifact) without reading the definition registry again. The change is
// additive: existing instances are unaffected (NULL). No index is created (hash is not used
// as a lookup key in this migration).
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    tenant_id: [16]u8,
    instance_id: [16]u8,
    definition_id: [16]u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    _ = conn;
    _ = allocator;
    // CUSTOM: realise per-test fixtures here (UUIDs, random strings, seed SQL).
    return Fixtures{
        .tenant_id = std.crypto.random.bytes(16),
        .instance_id = std.crypto.random.bytes(16),
        .definition_id = std.crypto.random.bytes(16),
    };
}

test "iss104_artifact_hash: add_artifact_hash_column_succeeds" {
    // The migration adds instances.artifact_hash as a nullable TEXT column.
    // covers: ISS-104
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    // The instances table exists (via migration 005_instances.sql).

    // Apply migration GBL-084.

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: SELECT column_name, data_type, is_nullable FROM information_schema.columns
    // WHERE table_name = 'instances' AND column_name = 'artifact_hash'
    // Assert: data_type = 'text', is_nullable = 'YES'.
}

test "iss104_artifact_hash: legacy_instances_unaffected" {
    // Pre-existing instances retain their data; artifact_hash is NULL for backward compatibility.
    // covers: ISS-104
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    // Insert a legacy instance row (before migration) via raw SQL:
    // INSERT INTO instances (instance_id, definition_id, definition_snapshot, ...)
    // VALUES (fx.instance_id, fx.definition_id, '{}', ...);

    // Apply migration GBL-084 (adds column with NULL default).

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: SELECT artifact_hash FROM instances WHERE instance_id = fx.instance_id
    // Assert: result is NULL.
    // Assert: row count unchanged (no rows deleted/added).
}

test "iss104_artifact_hash: new_instance_can_store_artifact_hash" {
    // After migration, an instance row can be inserted with a non-NULL artifact_hash.
    // covers: ISS-104
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    // Apply migration GBL-084.

    // INSERT INTO instances (..., artifact_hash) VALUES (..., fx.artifact_hash_sample);

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: SELECT artifact_hash FROM instances WHERE instance_id = fx.instance_id
    // Assert: result = fx.artifact_hash_sample.
}

test "iss104_artifact_hash: artifact_hash_nullable" {
    // The artifact_hash column allows NULL; no NOT NULL constraint exists.
    // covers: ISS-104
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    // Apply migration GBL-084.

    // INSERT INTO instances (..., artifact_hash) VALUES (..., NULL);

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert INSERT succeeds (no NOT NULL constraint violation).
}

test "iss104_artifact_hash: no_index_on_artifact_hash" {
    // No index is created on artifact_hash in this migration (hash is not a lookup key).
    // covers: ISS-104
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    // Apply migration GBL-084.

    // Query information_schema.statistics / pg_indexes for an index on artifact_hash.

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: Assert no index exists on instances(artifact_hash).
}
