// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/iss101_timers_failed_status_test.zig
// Requirements: ISS-101
//
// Extend the timers.status CHECK constraint to include 'failed', enabling the scheduler
// (ISS-303) to move exhausted-retry timers to a terminal FAILED state. Migration 015
// constrained status to (pending, fired, cancelled); this migration replaces that constraint
// with one that includes 'failed'. The change is additive: existing rows are unaffected
// (their values remain valid). The migration is idempotent: BACKEND-DEV wraps the constraint
// replacement in a DO $$ block that drops the old constraint before adding the new one.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

// ---------------------------------------------------------------------------
// CUSTOM: Per-test isolated UUIDs — fixed, valid v4 UUIDs for reproducibility.
// Each test block uses its own set of UUIDs so tests never interfere.
//
// The timers table lives in per-tenant schemas (not public). TestHarness
// connections default to search_path="$user",public. Each test sets search_path
// to tenant_default,public so unqualified table references resolve correctly.
// ---------------------------------------------------------------------------

const SCHEMA = "tenant_default";

/// Set search_path on conn to the test tenant schema so unqualified table
/// references (timers, instance_projections) resolve to the tenant schema.
fn setTenantSearchPath(conn: *pg.Conn) !void {
    try conn.exec("SET search_path TO tenant_default,public", &.{});
}

/// Insert a minimal instance_projections row so the timers FK is satisfied.
fn insertInstanceProjection(
    conn: *pg.Conn,
    instance_id_hex: []const u8,
) !void {
    // definition_id only needs to be a valid UUID — no FK check on it
    try conn.exec(
        \\INSERT INTO instance_projections
        \\    (instance_id, definition_id, status, last_event_seq)
        \\VALUES ($1::uuid, $2::uuid, 'ACTIVE', 0)
        \\ON CONFLICT (instance_id) DO NOTHING
    ,
        &.{ instance_id_hex, "00000000-1010-4000-8000-000000000000" },
    );
}

/// Insert a minimal timer row with status 'pending'.
fn insertPendingTimer(
    conn: *pg.Conn,
    timer_id_hex: []const u8,
    instance_id_hex: []const u8,
) !void {
    try conn.exec(
        \\INSERT INTO timers
        \\    (id, instance_id, timer_type, step_name, fires_at, action_type, action_config, status)
        \\VALUES
        \\    ($1::uuid, $2::uuid, 'scheduled_transition', 'WAIT_TIMER',
        \\     NOW() + INTERVAL '1 hour', 'auto_transition', '{}'::jsonb, 'pending')
    ,
        &.{ timer_id_hex, instance_id_hex },
    );
}

// ---------------------------------------------------------------------------

test "iss101_timers_failed_status: update_timer_to_failed_succeeds" {
    // A timer row can be updated to status 'failed' after the migration extends the CHECK constraint.
    // covers: ISS-101
    const allocator = std.testing.allocator;
    var h = try helpers.TestHarness.init(allocator);
    defer h.deinit();
    try setTenantSearchPath(&h.conn);

    // CUSTOM: per-test UUIDs — valid v4 form
    const instance_id = "10110000-0000-4000-8000-000000000001";
    const timer_id    = "10110000-0000-4000-8000-000000000002";

    try insertInstanceProjection(&h.conn, instance_id);
    try insertPendingTimer(&h.conn, timer_id, instance_id);

    // Act: update status to lowercase 'failed'
    try h.conn.exec(
        "UPDATE timers SET status = 'failed' WHERE id = $1::uuid",
        &.{timer_id},
    );

    // Assert: the row now has status = 'failed'
    var rows = try h.conn.query(
        allocator,
        "SELECT status FROM timers WHERE id = $1::uuid",
        &.{timer_id},
    );
    defer rows.deinit();

    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const status = rows.rows[0][0] orelse "";
    try std.testing.expectEqualStrings("failed", status);
}

test "iss101_timers_failed_status: update_timer_to_failed_uppercase_succeeds" {
    // The CHECK uses lower() so 'FAILED' (uppercase) is also accepted.
    // covers: ISS-101
    const allocator = std.testing.allocator;
    var h = try helpers.TestHarness.init(allocator);
    defer h.deinit();
    try setTenantSearchPath(&h.conn);

    // CUSTOM: distinct UUIDs from the previous test
    const instance_id = "10110000-0000-4000-8000-000000000003";
    const timer_id    = "10110000-0000-4000-8000-000000000004";

    try insertInstanceProjection(&h.conn, instance_id);
    try insertPendingTimer(&h.conn, timer_id, instance_id);

    // Act: update status to uppercase 'FAILED' — CHECK uses lower() so it passes
    try h.conn.exec(
        "UPDATE timers SET status = 'FAILED' WHERE id = $1::uuid",
        &.{timer_id},
    );

    // Assert: the row now has status = 'FAILED' (stored as-is; CHECK uses lower())
    var rows = try h.conn.query(
        allocator,
        "SELECT status FROM timers WHERE id = $1::uuid",
        &.{timer_id},
    );
    defer rows.deinit();

    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const status = rows.rows[0][0] orelse "";
    try std.testing.expectEqualStrings("FAILED", status);
}

test "iss101_timers_failed_status: invalid_status_still_rejected" {
    // An arbitrary invalid status value is rejected by the CHECK constraint even after migration.
    // covers: ISS-101
    //
    // A CHECK constraint violation (PG error 23514) aborts the current statement.
    // We use a SAVEPOINT so the outer transaction survives the violation and we can
    // verify the timer row is still in its original 'pending' state.
    const allocator = std.testing.allocator;
    var h = try helpers.TestHarness.init(allocator);
    defer h.deinit();
    try setTenantSearchPath(&h.conn);

    const instance_id = "10110000-0000-4000-8000-000000000005";
    const timer_id    = "10110000-0000-4000-8000-000000000006";

    try insertInstanceProjection(&h.conn, instance_id);
    try insertPendingTimer(&h.conn, timer_id, instance_id);

    // Establish a savepoint before the violating statement.
    try h.conn.exec("SAVEPOINT before_bogus", &.{});

    const update_result = h.conn.exec(
        "UPDATE timers SET status = 'BOGUS' WHERE id = $1::uuid",
        &.{timer_id},
    );

    // The UPDATE must fail with a server error (constraint violation 23514).
    try std.testing.expectError(error.ServerError, update_result);

    // Roll back to the savepoint to restore the transaction to a usable state.
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_bogus", &.{});

    // The timer status must still be 'pending' — the violating UPDATE was rejected.
    var rows = try h.conn.query(
        allocator,
        "SELECT status FROM timers WHERE id = $1::uuid",
        &.{timer_id},
    );
    defer rows.deinit();

    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const status = rows.rows[0][0] orelse "";
    try std.testing.expectEqualStrings("pending", status);
}

test "iss101_timers_failed_status: existing_statuses_remain_valid" {
    // Pre-existing status values (pending, fired, cancelled) still pass the constraint after migration.
    // covers: ISS-101
    const allocator = std.testing.allocator;
    var h = try helpers.TestHarness.init(allocator);
    defer h.deinit();
    try setTenantSearchPath(&h.conn);

    // CUSTOM: one instance, three timers — one per legacy status value
    const instance_id     = "10110000-0000-4000-8000-000000000007";
    const timer_pending   = "10110000-0000-4000-8000-000000000008";
    const timer_fired     = "10110000-0000-4000-8000-000000000009";
    const timer_cancelled = "10110000-0000-4000-800a-000000000001";

    try insertInstanceProjection(&h.conn, instance_id);

    // Insert timer with status 'pending'
    try h.conn.exec(
        \\INSERT INTO timers
        \\    (id, instance_id, timer_type, step_name, fires_at, action_type, action_config, status)
        \\VALUES
        \\    ($1::uuid, $2::uuid, 'scheduled_transition', 'STEP_PENDING',
        \\     NOW() + INTERVAL '1 hour', 'auto_transition', '{}'::jsonb, 'pending')
    ,
        &.{ timer_pending, instance_id },
    );

    // Insert timer with status 'fired'
    try h.conn.exec(
        \\INSERT INTO timers
        \\    (id, instance_id, timer_type, step_name, fires_at, action_type, action_config, status, fired_at)
        \\VALUES
        \\    ($1::uuid, $2::uuid, 'scheduled_transition', 'STEP_FIRED',
        \\     NOW() - INTERVAL '1 hour', 'auto_transition', '{}'::jsonb, 'fired', NOW())
    ,
        &.{ timer_fired, instance_id },
    );

    // Insert timer with status 'cancelled'
    try h.conn.exec(
        \\INSERT INTO timers
        \\    (id, instance_id, timer_type, step_name, fires_at, action_type, action_config, status, cancelled_at)
        \\VALUES
        \\    ($1::uuid, $2::uuid, 'scheduled_transition', 'STEP_CANCELLED',
        \\     NOW() - INTERVAL '2 hours', 'auto_transition', '{}'::jsonb, 'cancelled', NOW())
    ,
        &.{ timer_cancelled, instance_id },
    );

    // Assert: all three rows exist with their respective original status values.
    // ORDER BY status: cancelled, fired, pending
    var rows = try h.conn.query(
        allocator,
        \\SELECT id::text, status FROM timers
        \\WHERE id = ANY(ARRAY[$1::uuid, $2::uuid, $3::uuid])
        \\ORDER BY status
    ,
        &.{ timer_cancelled, timer_fired, timer_pending },
    );
    defer rows.deinit();

    try std.testing.expectEqual(@as(usize, 3), rows.rows.len);
    const s0 = rows.rows[0][1] orelse "";
    const s1 = rows.rows[1][1] orelse "";
    const s2 = rows.rows[2][1] orelse "";
    try std.testing.expectEqualStrings("cancelled", s0);
    try std.testing.expectEqualStrings("fired", s1);
    try std.testing.expectEqualStrings("pending", s2);
}
