// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/iss107_tenant_storage_mode_test.zig
// Requirements: ISS-107
//
// Add a storage_mode flag to the public.tenant table so each tenant has exactly one
// authoritative storage path during SPT (schema-per-tenant) coexistence. Valid values:
// LEGACY_RLS (existing RLS-based path) and SCHEMA (new schema-per-tenant path). Existing
// tenants default to LEGACY_RLS; newly provisioned tenants default to SCHEMA (set by the
// Zig-side provisionTenantSchema() function in src/db/provisioning.zig).
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    tenant_id: [16]u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    _ = conn;
    _ = allocator;
    // CUSTOM: realise per-test fixtures here (UUIDs, random strings, seed SQL).
    return Fixtures{
        .tenant_id = std.crypto.random.bytes(16),
    };
}

test "iss107_tenant_storage_mode: existing_tenant_defaults_to_legacy_rls" {
    // The default tenant (id='0000...0000') has storage_mode = 'LEGACY_RLS'.
    // covers: ISS-107
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    const row = try h.conn.queryRow(
      "SELECT storage_mode FROM tenant WHERE id = '00000000-0000-0000-0000-000000000000'",
      .{},
    );

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert row[0] equals "LEGACY_RLS"
}

test "iss107_tenant_storage_mode: check_constraint_rejects_invalid_mode" {
    // UPDATE with storage_mode = 'INVALID' is rejected by the CHECK constraint.
    // covers: ISS-107
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    try h.conn.exec(
      "UPDATE tenant SET storage_mode = 'INVALID' WHERE id = $1::uuid",
      .{fx.tenant_id},
    );

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert error.CheckConstraintViolation; SELECT shows the original value.
}

test "iss107_tenant_storage_mode: set_storage_mode_to_schema" {
    // A tenant can have storage_mode updated to 'SCHEMA'.
    // covers: ISS-107
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    try h.conn.exec(
      "UPDATE tenant SET storage_mode = 'SCHEMA' WHERE id = $1::uuid",
      .{fx.tenant_id},
    );

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert SELECT returns "SCHEMA"
}
