// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/obp01_plat_outbox_gate_depth_ts_test.zig
// Requirements: OBP-01, OBP-02
//
// Adds depth_refreshed_at to plat_outbox_gate so the drainer can record when it last
// refreshed the cached depth (OBP-01 AC3: a cached value older than 5 s is treated as at-
// cap). Also seeds EXECUTION_INGRESS_REFUSED in event_type_registry for OBP-02's async audit
// event append.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    tenant_schema: []u8,
    other_tenant_schema: []u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    _ = conn;
    _ = allocator;
    // CUSTOM: realise per-test fixtures here (UUIDs, random strings, seed SQL).
    return Fixtures{
        .tenant_schema = try allocator.dupe(u8, "fx_tenant_schema_REPLACE"),
        .other_tenant_schema = try allocator.dupe(u8, "fx_other_tenant_schema_REPLACE"),
    };
}

test "obp01_plat_outbox_gate_depth_ts: TC-OBP-01-depth-refreshed-at-exists" {
    // GIVEN the migration has run, WHEN plat_outbox_gate is inspected,
THEN depth_refreshed_at column exists and is NOT NULL.
    // covers: OBP-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    SELECT column_name, is_nullable
    FROM information_schema.columns
    WHERE table_name = 'plat_outbox_gate' AND column_name = 'depth_refreshed_at';

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert exactly 1 row is returned and is_nullable == 'NO',
    // confirming depth_refreshed_at exists on plat_outbox_gate and is NOT NULL.
}

test "obp01_plat_outbox_gate_depth_ts: TC-OBP-01-depth-refreshed-at-independent-of-state-transition" {
    // GIVEN a row with depth_refreshed_at = T0, WHEN only the gate state
column is updated (e.g. state flips from open to closed), THEN
depth_refreshed_at remains T0 (not advanced by the state update).
    // covers: OBP-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    UPDATE plat_outbox_gate SET state = 'closed' WHERE tenant_schema = $1;
    SELECT depth_refreshed_at FROM plat_outbox_gate WHERE tenant_schema = $1;

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert depth_refreshed_at for the row equals the value inserted
    // during seed_gate_row (i.e. it was not advanced by the state-column UPDATE).
}

test "obp01_plat_outbox_gate_depth_ts: TC-OBP-01-stale-after-5s" {
    // GIVEN depth_refreshed_at is set to now() - interval '6 seconds',
WHEN the middleware reads the row, THEN it observes is_stale=true
and treats depth as at-cap.
    // covers: OBP-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    UPDATE plat_outbox_gate
      SET depth_refreshed_at = now() - interval '6 seconds'
      WHERE tenant_schema = $1;

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert the row's depth_refreshed_at is more than 5 s in the past
    // and that middleware logic treats this as is_stale = true (depth is at-cap).
}

test "obp01_plat_outbox_gate_depth_ts: TC-OBP-02-ingress-refused-event-seeded" {
    // GIVEN the migration has run in a tenant schema, WHEN event_type_registry
is queried for EXECUTION_INGRESS_REFUSED, THEN one row is returned.
    // covers: OBP-02
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, h.conn);
    _ = fx;

    SELECT COUNT(*)::int AS n FROM event_type_registry
    WHERE name = 'EXECUTION_INGRESS_REFUSED';

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // CUSTOM: assert n == 1, confirming EXECUTION_INGRESS_REFUSED was seeded
    // exactly once in event_type_registry for this tenant schema.
}
