// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/obp04_plat_outbox_gate_test.zig
// Requirements: OBP-04
//
// Creates plat_outbox_gate, one row per tenant schema recording the outbox ingress gate
// state (open/closed), the last observed depth, the cap and the 80% low-water hysteresis
// mark, the timestamp of the last transition, and the AC4/AC5 escalation counters (refusal
// window + closed duration). The gate module (src/outbox/gate.zig) persists every transition
// here in one transaction with the EXECUTION_OUTBOX_GATE_OPENED event append (OBP-04 AC2);
// the row is keyed by tenant_schema so one tenant's depth never refuses another tenant's
// ingress (OBP-04 AC6). low_water is writable so the flapping recovery (OBP-04 AC3) can
// restore the 80% hysteresis mark in place.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    tenant_schema_value: []u8,
    other_tenant_schema_value: []u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    // CUSTOM: realise per-test fixtures here (random strings + the two gate seeds).
    const tenant_schema_value = try allocator.dupe(u8, "obp04-tenant-00000000-0000-0000-0000-000000000001");
    errdefer allocator.free(tenant_schema_value);
    const other_tenant_schema_value = try allocator.dupe(u8, "obp04-tenant-00000000-0000-0000-0000-000000000002");
    errdefer allocator.free(other_tenant_schema_value);

    // seed_closed_gate — closed 400 s ago at depth 49999, cap 50000, low-water 40000.
    try conn.exec(
        \\INSERT INTO plat_outbox_gate
        \\  (tenant_schema, state, depth, cap, low_water, closed_at, closed_duration_ms)
        \\VALUES
        \\  ($1, 'closed', 49999, 50000, 40000, now() - interval '400 seconds', 0)
    ,
        &.{tenant_schema_value},
    );
    // seed_open_gate_other_tenant — a second tenant's OPEN gate at depth 1000.
    try conn.exec(
        \\INSERT INTO plat_outbox_gate
        \\  (tenant_schema, state, depth, cap, low_water)
        \\VALUES
        \\  ($1, 'open', 1000, 50000, 40000)
    ,
        &.{other_tenant_schema_value},
    );

    return Fixtures{
        .tenant_schema_value = tenant_schema_value,
        .other_tenant_schema_value = other_tenant_schema_value,
    };
}

fn freeFixtures(allocator: std.mem.Allocator, fx: Fixtures) void {
    allocator.free(fx.tenant_schema_value);
    allocator.free(fx.other_tenant_schema_value);
}

test "obp04_plat_outbox_gate: per_tenant_keying_keeps_rows_independent" {
    // OBP-04 AC6 — two tenants have independent gate rows; one tenant's closed state and depth never affect the other's row.
    // covers: OBP-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    var result = try h.conn.query(std.testing.allocator,
        "SELECT state, depth FROM plat_outbox_gate ORDER BY tenant_schema",
        &.{});
    defer result.deinit();

    // CUSTOM: assert exactly 2 rows: one 'closed' with depth 49999 for
    // fx.tenant_schema_value and one 'open' with depth 1000 for
    // fx.other_tenant_schema_value — the closed tenant's depth does not
    // touch the other tenant's row.
    try std.testing.expectEqual(@as(usize, 2), result.rows.len);
    var saw_closed = false;
    var saw_open = false;
    for (result.rows) |row| {
        if (row.len < 2 or row[0] == null or row[1] == null) continue;
        if (std.mem.eql(u8, row[0].?, "closed") and std.mem.eql(u8, row[1].?, "49999")) saw_closed = true;
        if (std.mem.eql(u8, row[0].?, "open") and std.mem.eql(u8, row[1].?, "1000")) saw_open = true;
    }
    try std.testing.expect(saw_closed);
    try std.testing.expect(saw_open);
}

test "obp04_plat_outbox_gate: state_check_constraint_rejects_unknown_value" {
    // A state outside open/closed is rejected by the CHECK constraint.
    // covers: OBP-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: SAVEPOINT must precede the failing insert (Postgres aborts the
    // transaction on error; only ROLLBACK TO SAVEPOINT recovers it).
    try h.conn.exec("SAVEPOINT before_flapping", &.{});
    const result = h.conn.exec(
        "INSERT INTO plat_outbox_gate (tenant_schema, state, cap, low_water) VALUES ($1, 'flapping', 50000, 40000)",
        &.{fx.tenant_schema_value},
    );

    // CUSTOM: assert error.CheckConstraintViolation (SQLSTATE 23514) and that
    // exactly one row exists for fx.tenant_schema_value (the seeded one).
    try std.testing.expectError(error.ServerError, result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_flapping", &.{});

    var rows = try h.conn.query(std.testing.allocator,
        "SELECT count(*) FROM plat_outbox_gate WHERE tenant_schema = $1",
        &.{fx.tenant_schema_value});
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("1", rows.rows[0][0] orelse "0");
}

test "obp04_plat_outbox_gate: low_water_must_be_below_cap" {
    // The 80% hysteresis invariant — low_water must be strictly below cap. A row with low_water equal to or above cap (the AC3 misconfiguration) is rejected by the CHECK constraint, so a gate can never be configured to reopen at the cap.
    // covers: OBP-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: SAVEPOINT must precede the failing insert.
    try h.conn.exec("SAVEPOINT before_lw_equal_cap", &.{});
    const result = h.conn.exec(
        "INSERT INTO plat_outbox_gate (tenant_schema, state, cap, low_water) VALUES ($1, 'open', 50000, 50000)",
        &.{fx.other_tenant_schema_value},
    );

    // CUSTOM: assert error.CheckConstraintViolation (23514); the AC3 defect
    // (low_water == cap) cannot be persisted — it must be repaired by restoring
    // low_water to floor(cap * 4 / 5) = 40000 instead.
    try std.testing.expectError(error.ServerError, result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_lw_equal_cap", &.{});
}

test "obp04_plat_outbox_gate: low_water_must_be_below_cap_above_cap" {
    // low_water strictly above cap is also rejected by the CHECK constraint.
    // covers: OBP-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: SAVEPOINT must precede the failing insert.
    try h.conn.exec("SAVEPOINT before_lw_above_cap", &.{});
    const result = h.conn.exec(
        "INSERT INTO plat_outbox_gate (tenant_schema, state, cap, low_water) VALUES ($1, 'open', 50000, 60000)",
        &.{fx.other_tenant_schema_value},
    );

    try std.testing.expectError(error.ServerError, result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_lw_above_cap", &.{});
}

test "obp04_plat_outbox_gate: closed_gate_sweep_finds_long_closed_tenant" {
    // OBP-04 AC5 — the partial index over closed gates ordered by closed_at finds a gate closed longer than 300 s (seeded closed 400 s ago) without scanning open gates.
    // covers: OBP-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    var result = try h.conn.query(std.testing.allocator,
        "SELECT tenant_schema, closed_at FROM plat_outbox_gate WHERE state = 'closed' AND closed_at <= now() - interval '300 seconds' ORDER BY closed_at",
        &.{});
    defer result.deinit();

    // CUSTOM: assert result.rows.len == 1 and tenant_schema ==
    // fx.tenant_schema_value (the open gate for fx.other_tenant_schema_value is
    // excluded), confirming the AC5 sweep scans only closed gates.
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    try std.testing.expect(result.rows[0].len >= 1);
    try std.testing.expectEqualStrings(fx.tenant_schema_value, result.rows[0][0] orelse "");
}

test "obp04_plat_outbox_gate: reopen_persists_transition_and_duration" {
    // OBP-04 AC2 — the reopen transition persists state='open', stamps last_transition_at, and records the closed duration, so the EXECUTION_OUTBOX_GATE_OPENED event can carry it.
    // covers: OBP-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "UPDATE plat_outbox_gate SET state = 'open', depth = 40000, closed_duration_ms = extract(epoch from (now() - closed_at))::bigint * 1000, last_transition_at = now(), updated_at = now() WHERE tenant_schema = $1",
        &.{fx.tenant_schema_value},
    );

    // CUSTOM: assert the row for fx.tenant_schema_value now reads state='open',
    // depth=40000, closed_duration_ms >= 400000 (400 s from the seed), and
    // last_transition_at has been refreshed — the data the AC2 event carries.
    var rows = try h.conn.query(std.testing.allocator,
        "SELECT state, depth, closed_duration_ms FROM plat_outbox_gate WHERE tenant_schema = $1",
        &.{fx.tenant_schema_value});
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const row = rows.rows[0];
    try std.testing.expect(row.len >= 3);
    try std.testing.expectEqualStrings("open", row[0] orelse "");
    try std.testing.expectEqualStrings("40000", row[1] orelse "");
    const duration = std.fmt.parseInt(u64, row[2] orelse "0", 10) catch 0;
    try std.testing.expect(duration >= 400000);
}
