// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/ord04_plat_correlation_cursor_test.zig
// Requirements: ORD-04, ORD-02
//
// Creates plat_correlation_cursor, one row per correlation_id carrying the highest
// sequence_no successfully applied (applied_seq). ORD-02's execute guard reads this value
// while holding the per-correlation advisory lock (process doc step 4); ORD-04's lag metric
// is max(sequence_no) [from plat_effect_completion] minus applied_seq per correlation_id,
// read directly off this table with no separate aggregate table needed. ORD-03 (a later
// batch) owns the conditional UPDATE ... WHERE applied_seq = $2 - 1 cursor-advance statement
// and the MissingCursorRow recovery (insert at applied_seq=0) — this migration only creates
// the table shape both ORD-02 (read-only, this batch) and ORD-03 (read-write, later batch)
// need, per the Type E design's explicit statement that ORD-03's design must not need a
// schema change here.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.
//
// CUSTOM: uses a real bpm.pool.Pool (not TestHarness), matching
// ord01_plat_effect_completion_test.zig's rationale — the lag-computation test
// case joins plat_correlation_cursor against plat_effect_completion, and
// every fixture row here is autocommitted (and explicitly deleted in
// `defer`) so it is genuinely visible to whichever connection runs the join.

const std = @import("std");
const portable_env = @import("env");
const bpm = @import("bpm");
const Pool = bpm.pool.Pool;
const PoolConfig = bpm.pool.PoolConfig;

fn testDbUrl(allocator: std.mem.Allocator) ![]u8 {
    const env = portable_env.globalEnviron();
    return env.getAlloc(allocator, "BPM_TEST_DB_URL") catch |err| switch (err) {
        error.EnvironmentVariableMissing => {
            std.debug.print("BPM_TEST_DB_URL is not set — skipping ORD-04 integration tests\n", .{});
            return error.SkipZigTest;
        },
        else => return err,
    };
}

fn makePool(allocator: std.mem.Allocator, url: []const u8) !Pool {
    bpm.api_tenant_context.set("00000000-0000-0000-0000-000000000000");
    return Pool.init(std.testing.io, allocator, PoolConfig{
        .url = url,
        .pool_size = 5,
    });
}

const Fixtures = struct {
    correlation_a: []const u8,

    fn init(allocator: std.mem.Allocator) !Fixtures {
        return Fixtures{
            .correlation_a = try bpm.uuid.newUuidV4(allocator),
        };
    }

    fn deinit(self: Fixtures, allocator: std.mem.Allocator) void {
        allocator.free(self.correlation_a);
    }
};

fn cleanup(conn: *bpm.pool.Conn, correlation_id: []const u8) void {
    conn.exec("DELETE FROM plat_effect_completion WHERE correlation_id = $1", &.{correlation_id}) catch {};
    conn.exec("DELETE FROM plat_correlation_cursor WHERE correlation_id = $1", &.{correlation_id}) catch {};
}

test "ord04_plat_correlation_cursor: insert_then_read_applied_seq" {
    // A newly inserted cursor row is retrievable and starts at the seeded applied_seq.
    // covers: ORD-04
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const conn = try pool.acquire();
    defer pool.release(conn);
    defer cleanup(conn, fx.correlation_a);

    try conn.exec(
        "INSERT INTO plat_correlation_cursor (correlation_id, applied_seq) VALUES ($1, 4)",
        &.{fx.correlation_a},
    );

    var result = try conn.query(
        allocator,
        "SELECT applied_seq FROM plat_correlation_cursor WHERE correlation_id = $1",
        &.{fx.correlation_a},
    );
    defer result.deinit();

    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    try std.testing.expectEqualStrings("4", result.rows[0][0] orelse "");
}

test "ord04_plat_correlation_cursor: primary_key_prevents_duplicate_correlation_row" {
    // A second INSERT for the same correlation_id without ON CONFLICT fails — proves the PK enforces exactly one cursor row per correlation, which ORD-02's execute guard (reading this row while holding the advisory lock keyed on the same correlation_id) depends on for a well-defined read.
    // covers: ORD-04
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const conn = try pool.acquire();
    defer pool.release(conn);
    defer cleanup(conn, fx.correlation_a);

    try conn.exec(
        "INSERT INTO plat_correlation_cursor (correlation_id, applied_seq) VALUES ($1, 4)",
        &.{fx.correlation_a},
    );

    const dup_result = conn.exec(
        "INSERT INTO plat_correlation_cursor (correlation_id, applied_seq) VALUES ($1, 0)",
        &.{fx.correlation_a},
    );
    try std.testing.expectError(error.QueryFailed, dup_result);

    // SELECT still returns exactly 1 row with applied_seq == "4" (unchanged).
    var result = try conn.query(
        allocator,
        "SELECT applied_seq FROM plat_correlation_cursor WHERE correlation_id = $1",
        &.{fx.correlation_a},
    );
    defer result.deinit();
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    try std.testing.expectEqualStrings("4", result.rows[0][0] orelse "");
}

test "ord04_plat_correlation_cursor: applied_seq_check_constraint_rejects_negative" {
    // applied_seq cannot go negative — CHECK constraint enforced.
    // covers: ORD-04
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const conn = try pool.acquire();
    defer pool.release(conn);
    defer cleanup(conn, fx.correlation_a);

    // Use fx.correlation_a (fresh per-test UUID) rather than a static literal,
    // per the per-test-UUID fixture convention — the YAML spec's
    // "other-correlation-not-yet-seeded" literal is replaced here.
    const result = conn.exec(
        "INSERT INTO plat_correlation_cursor (correlation_id, applied_seq) VALUES ($1, -1)",
        &.{fx.correlation_a},
    );
    try std.testing.expectError(error.QueryFailed, result);

    var rows = try conn.query(
        allocator,
        "SELECT count(*) FROM plat_correlation_cursor WHERE correlation_id = $1",
        &.{fx.correlation_a},
    );
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("0", rows.rows[0][0] orelse "0");
}

test "ord04_plat_correlation_cursor: lag_computable_via_join_against_completion_table" {
    // ORD-04 AC2's lag formula (max(sequence_no) - applied_seq) is computable directly by joining plat_effect_completion against this table, with no extra schema needed — smoke-tests the two Type C migrations' compatibility with each other.
    // covers: ORD-04
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const conn = try pool.acquire();
    defer pool.release(conn);
    defer cleanup(conn, fx.correlation_a);

    try conn.exec(
        "INSERT INTO plat_correlation_cursor (correlation_id, applied_seq) VALUES ($1, 4)",
        &.{fx.correlation_a},
    );
    try conn.exec(
        "INSERT INTO plat_effect_completion (correlation_id, sequence_no, status) VALUES ($1, 5, 'PENDING'), ($1, 6, 'PENDING')",
        &.{fx.correlation_a},
    );

    var result = try conn.query(
        allocator,
        \\SELECT MAX(pec.sequence_no) - pcc.applied_seq AS lag
        \\FROM plat_effect_completion pec
        \\JOIN plat_correlation_cursor pcc ON pcc.correlation_id = pec.correlation_id
        \\WHERE pec.correlation_id = $1
        \\GROUP BY pcc.applied_seq
    ,
        &.{fx.correlation_a},
    );
    defer result.deinit();

    // max sequence_no 6 minus seeded applied_seq 4 = 2.
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    try std.testing.expectEqualStrings("2", result.rows[0][0] orelse "");
}
