// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/ord01_plat_effect_completion_test.zig
// Requirements: ORD-01, ORD-02, ORD-04
//
// Creates plat_effect_completion, the table BPM Consumers poll to claim and apply correlated
// effect completions in order. One row per completion; status starts PENDING, becomes
// APPLIED (ORD-03, a later batch) or DEAD (ORD-03's gap sweeper, a later batch). This batch
// (ORD-01/02/04) only claims and observes rows via FOR UPDATE SKIP LOCKED plus a per-
// correlation advisory lock; it never transitions status away from PENDING — see the Type E
// design's "State transitions" section.  Columns follow docs/processes/system/effect-
// reentry-ordering.md's Inputs table exactly: completion_id (PK), correlation_id,
// sequence_no, status, payload, received_at. (correlation_id, sequence_no) is UNIQUE so a
// retried Effects Worker insert is absorbed by ON CONFLICT DO NOTHING (process doc step 1 /
// Business Rules "Duplicate completions"), and the claim index matches the ORD-01 claim
// query's exact WHERE/ORDER BY shape (status='PENDING' ORDER BY correlation_id,
// sequence_no).
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.
//
// CUSTOM: uses a real bpm.pool.Pool (not TestHarness) throughout, since the
// claim_query_skip_locked_excludes_locked_row test case needs two genuinely
// separate connections whose row locks are visible to one another —
// TestHarness wraps its single connection in a transaction that only ever
// rolls back, so a fixture seeded through it is invisible to any other
// connection (see tests/integration/effects_subsystem_test.zig's
// EffectsPoolFixture comment for the same constraint). Every fixture row this
// file inserts is therefore autocommitted and explicitly deleted in `defer`,
// per docs/anti-patterns.md's autocommitted-fixture entry: every UNIQUE-ish
// value used is a fresh per-test UUID, never a static literal.

const std = @import("std");
const portable_env = @import("env");
const bpm = @import("bpm");
const Pool = bpm.pool.Pool;
const PoolConfig = bpm.pool.PoolConfig;

fn testDbUrl(allocator: std.mem.Allocator) ![]u8 {
    const env = portable_env.globalEnviron();
    return env.getAlloc(allocator, "BPM_TEST_DB_URL") catch |err| switch (err) {
        error.EnvironmentVariableMissing => {
            std.debug.print("BPM_TEST_DB_URL is not set — skipping ORD-01 integration tests\n", .{});
            return error.SkipZigTest;
        },
        else => return err,
    };
}

fn makePool(allocator: std.mem.Allocator, url: []const u8) !Pool {
    // Set the tenant context BEFORE Pool.init so that every pool.acquire()
    // applies the same search_path routing (see the ISS-0145 anti-pattern on
    // ambient tenant_context ordering).
    bpm.api_tenant_context.set("00000000-0000-0000-0000-000000000000");
    return Pool.init(std.testing.io, allocator, PoolConfig{
        .url = url,
        .pool_size = 5,
    });
}

const Fixtures = struct {
    correlation_a: []const u8,
    correlation_b: []const u8,

    fn init(allocator: std.mem.Allocator) !Fixtures {
        return Fixtures{
            .correlation_a = try bpm.uuid.newUuidV4(allocator),
            .correlation_b = try bpm.uuid.newUuidV4(allocator),
        };
    }

    fn deinit(self: Fixtures, allocator: std.mem.Allocator) void {
        allocator.free(self.correlation_a);
        allocator.free(self.correlation_b);
    }
};

/// Delete every autocommitted row this fixture may have created. Registered
/// with `defer` before any insert, so it runs even if the test body fails
/// mid-way.
fn cleanup(conn: *bpm.pool.Conn, fx: Fixtures) void {
    conn.exec("DELETE FROM plat_effect_completion WHERE correlation_id = $1", &.{fx.correlation_a}) catch {};
    conn.exec("DELETE FROM plat_effect_completion WHERE correlation_id = $1", &.{fx.correlation_b}) catch {};
}

test "ord01_plat_effect_completion: claim_query_skip_locked_excludes_locked_row" {
    // ORD-01 AC1 — with one PENDING row locked by a concurrent transaction, a second transaction's claim query (FOR UPDATE SKIP LOCKED) returns no row rather than blocking or erroring.
    // covers: ORD-01
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const seed_conn = try pool.acquire();
    defer pool.release(seed_conn);
    defer cleanup(seed_conn, fx);

    try seed_conn.exec(
        "INSERT INTO plat_effect_completion (correlation_id, sequence_no, status, payload) VALUES ($1, 1, 'PENDING', '{\"outcome\":\"ok\"}'::jsonb)",
        &.{fx.correlation_a},
    );
    try seed_conn.exec(
        "INSERT INTO plat_effect_completion (correlation_id, sequence_no, status, payload) VALUES ($1, 2, 'PENDING', '{\"outcome\":\"ok\"}'::jsonb)",
        &.{fx.correlation_a},
    );

    // Open a second connection and BEGIN + claim the seeded row there first,
    // leaving it locked (uncommitted) for the duration of this test.
    const locker = try pool.acquire();
    var locker_rolled_back = false;
    defer if (!locker_rolled_back) locker.rollback() catch {};
    defer pool.release(locker);
    try locker.begin();
    var locked_result = try locker.query(
        allocator,
        "SELECT completion_id, sequence_no FROM plat_effect_completion WHERE status = 'PENDING' AND correlation_id = $1 ORDER BY correlation_id, sequence_no FOR UPDATE SKIP LOCKED LIMIT 1",
        &.{fx.correlation_a},
    );
    defer locked_result.deinit();
    try std.testing.expectEqual(@as(usize, 1), locked_result.rows.len);
    try std.testing.expectEqualStrings("1", locked_result.rows[0][1] orelse "");

    const claimer = try pool.acquire();
    defer pool.release(claimer);
    var result = try claimer.query(
        allocator,
        "SELECT completion_id, sequence_no FROM plat_effect_completion WHERE status = 'PENDING' AND correlation_id = $1 ORDER BY correlation_id, sequence_no FOR UPDATE SKIP LOCKED LIMIT 1",
        &.{fx.correlation_a},
    );
    defer result.deinit();

    // The locker holds sequence_no=1 uncommitted; this connection's claim
    // query must SKIP that locked row and return sequence_no=2 instead of
    // blocking or erroring (this call having returned at all, rather than
    // hanging, is itself evidence SKIP LOCKED did not block).
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    try std.testing.expectEqualStrings("2", result.rows[0][1] orelse "");

    locker.rollback() catch {};
    locker_rolled_back = true;
}

test "ord01_plat_effect_completion: duplicate_correlation_sequence_absorbed_by_on_conflict" {
    // Business rule "Duplicate completions" — a retried insert of the same (correlation_id, sequence_no) is a no-op under ON CONFLICT DO NOTHING, not a unique-violation error, once the caller uses that clause.
    // covers: ORD-01
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const conn = try pool.acquire();
    defer pool.release(conn);
    defer cleanup(conn, fx);

    try conn.exec(
        "INSERT INTO plat_effect_completion (correlation_id, sequence_no, status, payload) VALUES ($1, 1, 'PENDING', '{}'::jsonb) ON CONFLICT (correlation_id, sequence_no) DO NOTHING",
        &.{fx.correlation_a},
    );
    // Retry the exact same insert — must be absorbed, not error.
    try conn.exec(
        "INSERT INTO plat_effect_completion (correlation_id, sequence_no, status, payload) VALUES ($1, 1, 'PENDING', '{}'::jsonb) ON CONFLICT (correlation_id, sequence_no) DO NOTHING",
        &.{fx.correlation_a},
    );

    var result = try conn.query(
        allocator,
        "SELECT completion_id FROM plat_effect_completion WHERE correlation_id = $1 AND sequence_no = 1",
        &.{fx.correlation_a},
    );
    defer result.deinit();

    // Exactly 1 row exists — the duplicate insert did not create a second row
    // and did not error.
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
}

test "ord01_plat_effect_completion: status_check_constraint_rejects_unknown_value" {
    // A status outside PENDING/APPLIED/DEAD is rejected by the CHECK constraint.
    // covers: ORD-01
    const allocator = std.testing.allocator;
    const url = try testDbUrl(allocator);
    defer allocator.free(url);
    var pool = try makePool(allocator, url);
    defer pool.deinit();

    const fx = try Fixtures.init(allocator);
    defer fx.deinit(allocator);

    const conn = try pool.acquire();
    defer pool.release(conn);
    defer cleanup(conn, fx);

    // pg.Conn's exec() surfaces every server-side error as error.ServerError
    // (the SQLSTATE itself is not threaded through the pool abstraction — see
    // src/db/pool.zig's Conn.exec), matching every other CHECK-constraint
    // test in this repo (tests/integration/platform_migrations_control_table_test.zig,
    // tests/integration/iss107_tenant_storage_mode_test.zig).
    const result = conn.exec(
        "INSERT INTO plat_effect_completion (correlation_id, sequence_no, status) VALUES ($1, 99, 'BOGUS')",
        &.{fx.correlation_b},
    );
    try std.testing.expectError(error.QueryFailed, result);

    var rows = try conn.query(
        allocator,
        "SELECT count(*) FROM plat_effect_completion WHERE correlation_id = $1",
        &.{fx.correlation_b},
    );
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("0", rows.rows[0][0] orelse "0");
}
