// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/platform_migrations_control_table_test.zig
// Requirements: MIG-01
//
// Introduce platform.platform_migrations, the single cross-tenant control table recording
// per-(migration_id, tenant_id) migration status (pending/done/failed). This is the control-
// row half of the transactional commit-with-DDL semantics MIG-02 defines and the fanout loop
// MIG-03 drives; it replaces reliance on the per-schema public.schema_migrations table as
// the only record of platform migration state. See src/design/mig-02-mig-03-platform-
// migration-fanout.md for the fanout logic that writes and reads this table. This migration
// only creates the schema and table/index shape; it contains no fanout logic (that is Type
// E, not Type C, per templates/lego-catalog.md's selection rules).
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    tenant_id: []const u8,
    migration_id_value: []u8,
    run_id_value: []u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    // CUSTOM: realise per-test fixtures here (UUIDs, random strings, seed SQL).
    //
    // CUSTOM: the codegen template's default `kind: uuid` fixture materialises
    // a raw [16]u8 array, which is NOT a valid text-format SQL parameter (the
    // `uuid` column expects the canonical 36-char hyphenated string, and the
    // pg wire protocol's text-format bind sends parameter bytes as-is with no
    // implicit binary-to-text conversion). tenant_id is therefore generated
    // here as its canonical string form instead, mirroring the pattern every
    // other integration test in this repo uses (helpers.zig's
    // TestHarness.newUuidString / uuidBytesToString).
    var raw_uuid: [16]u8 = undefined;
    std.testing.io.random(&raw_uuid);
    const tenant_id_str = try helpers.uuidBytesToString(allocator, raw_uuid);

    // migration_id / run_id: random per-test strings so concurrent test runs
    // (and repeated runs against a long-lived bpm_test container) never
    // collide on the UNIQUE (migration_id, tenant_id) anchor.
    var suffix_bytes: [8]u8 = undefined;
    std.testing.io.random(&suffix_bytes);
    const migration_id_value = try std.fmt.allocPrint(
        allocator,
        "mig_test_{x}",
        .{std.fmt.bytesToHex(&suffix_bytes, .lower)},
    );
    var run_suffix_bytes: [8]u8 = undefined;
    std.testing.io.random(&run_suffix_bytes);
    const run_id_value = try std.fmt.allocPrint(
        allocator,
        "run_test_{x}",
        .{std.fmt.bytesToHex(&run_suffix_bytes, .lower)},
    );

    _ = conn;
    return Fixtures{
        .tenant_id = tenant_id_str,
        .migration_id_value = migration_id_value,
        .run_id_value = run_id_value,
    };
}

fn freeFixtures(allocator: std.mem.Allocator, fx: Fixtures) void {
    allocator.free(fx.tenant_id);
    allocator.free(fx.migration_id_value);
    allocator.free(fx.run_id_value);
}

test "platform_migrations_control_table: unique_constraint_on_migration_tenant_pair" {
    // A second INSERT for the same (migration_id, tenant_id) violates the UNIQUE anchor used by the upsert.
    // covers: MIG-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "INSERT INTO platform.platform_migrations (migration_id, tenant_id, status) VALUES ($1, $2::uuid, 'pending')",
        &.{ fx.migration_id_value, fx.tenant_id },
    );

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // A duplicate (migration_id, tenant_id) INSERT must raise a real Postgres
    // server error (23505 unique_violation on
    // platform_migrations_migration_tenant_uq). Bracket with a SAVEPOINT so
    // the outer harness transaction is not itself aborted by the error,
    // matching the established pattern in
    // tests/integration/iss107_tenant_storage_mode_test.zig.
    try h.conn.exec("SAVEPOINT before_dup_insert", &.{});
    const dup_result = h.conn.exec(
        "INSERT INTO platform.platform_migrations (migration_id, tenant_id, status) VALUES ($1, $2::uuid, 'pending')",
        &.{ fx.migration_id_value, fx.tenant_id },
    );
    try std.testing.expectError(error.ServerError, dup_result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_dup_insert", &.{});

    // Exactly one row exists for (migration_id_value, tenant_id).
    var rows = try h.conn.query(
        std.testing.allocator,
        "SELECT count(*) FROM platform.platform_migrations WHERE migration_id = $1 AND tenant_id = $2::uuid",
        &.{ fx.migration_id_value, fx.tenant_id },
    );
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const count_str = rows.rows[0][0] orelse "0";
    try std.testing.expectEqualStrings("1", count_str);
}

test "platform_migrations_control_table: status_check_constraint_rejects_unknown_value" {
    // A status outside pending/done/failed is rejected by the CHECK constraint.
    // covers: MIG-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // assert error.CheckConstraintViolation (SQLSTATE 23514) and that no row
    // was inserted. pg.Conn's exec() surfaces every server-side error as
    // error.ServerError (the SQLSTATE itself is not threaded through the pool
    // abstraction — see src/db/pool.zig's Conn.exec), matching the pattern
    // used by every other CHECK-constraint test in this repo
    // (tests/integration/iss107_tenant_storage_mode_test.zig,
    // tests/integration/iss101_timers_failed_status_test.zig).
    try h.conn.exec("SAVEPOINT before_bogus_status", &.{});
    const bogus_result = h.conn.exec(
        "INSERT INTO platform.platform_migrations (migration_id, tenant_id, status) VALUES ($1, $2::uuid, 'bogus')",
        &.{ fx.migration_id_value, fx.tenant_id },
    );
    try std.testing.expectError(error.ServerError, bogus_result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_bogus_status", &.{});

    var rows = try h.conn.query(
        std.testing.allocator,
        "SELECT count(*) FROM platform.platform_migrations WHERE migration_id = $1 AND tenant_id = $2::uuid",
        &.{ fx.migration_id_value, fx.tenant_id },
    );
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const count_str = rows.rows[0][0] orelse "0";
    try std.testing.expectEqualStrings("0", count_str);
}

test "platform_migrations_control_table: failed_row_carries_error_msg_and_null_completed_at" {
    // A failed tenant row records error_msg and leaves completed_at null (MIG-01 AC4).
    // covers: MIG-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "INSERT INTO platform.platform_migrations (migration_id, tenant_id, status, error_msg, run_id) VALUES ($1, $2::uuid, 'failed', $3, $4)",
        &.{ fx.migration_id_value, fx.tenant_id, "23505: duplicate key value", fx.run_id_value },
    );

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // assert SELECT returns status='failed', error_msg matches the inserted
    // SQLSTATE+message text, and completed_at IS NULL.
    var rows = try h.conn.query(
        std.testing.allocator,
        "SELECT status, error_msg, completed_at FROM platform.platform_migrations WHERE migration_id = $1 AND tenant_id = $2::uuid",
        &.{ fx.migration_id_value, fx.tenant_id },
    );
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const row = rows.rows[0];
    try std.testing.expectEqualStrings("failed", row[0] orelse "");
    try std.testing.expectEqualStrings("23505: duplicate key value", row[1] orelse "");
    try std.testing.expect(row[2] == null);
}

test "platform_migrations_control_table: done_row_carries_completed_at_and_null_error_msg" {
    // A succeeded tenant row sets completed_at and leaves error_msg null (MIG-01 AC5).
    // covers: MIG-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "INSERT INTO platform.platform_migrations (migration_id, tenant_id, status, completed_at, run_id) VALUES ($1, $2::uuid, 'done', now(), $3)",
        &.{ fx.migration_id_value, fx.tenant_id, fx.run_id_value },
    );

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // assert SELECT returns status='done', completed_at IS NOT NULL, and
    // error_msg IS NULL.
    var rows = try h.conn.query(
        std.testing.allocator,
        "SELECT status, error_msg, completed_at FROM platform.platform_migrations WHERE migration_id = $1 AND tenant_id = $2::uuid",
        &.{ fx.migration_id_value, fx.tenant_id },
    );
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const row = rows.rows[0];
    try std.testing.expectEqualStrings("done", row[0] orelse "");
    try std.testing.expect(row[1] == null);
    try std.testing.expect(row[2] != null);
}

test "platform_migrations_control_table: resume_index_used_by_pending_or_failed_query" {
    // The resume-shaped query (migration_id + status IN pending/failed) is served by platform_migrations_resume_idx (MIG-01 AC3).
    // covers: MIG-01
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "INSERT INTO platform.platform_migrations (migration_id, tenant_id, status) VALUES ($1, $2::uuid, 'pending')",
        &.{ fx.migration_id_value, fx.tenant_id },
    );

    // The test table has only a handful of rows, so Postgres's planner would
    // legitimately prefer a sequential scan over an index scan on cost
    // grounds alone regardless of whether platform_migrations_resume_idx
    // exists — that would make this assertion flaky rather than a genuine
    // test of "the resume query IS SERVED BY the index" (MIG-01 AC3). Force
    // index usage for the EXPLAIN so the assertion is deterministic; this
    // still fails loudly if the planner cannot use
    // platform_migrations_resume_idx at all (e.g. wrong columns/predicate).
    try h.conn.exec("SET LOCAL enable_seqscan = off", &.{});

    var plan = try h.conn.query(
        std.testing.allocator,
        "EXPLAIN SELECT * FROM platform.platform_migrations WHERE migration_id = $1 AND status IN ('pending', 'failed')",
        &.{fx.migration_id_value},
    );
    defer plan.deinit();

    // CUSTOM: assertions for this test case — handwritten by the implementer.
    // assert the EXPLAIN output text contains "platform_migrations_resume_idx".
    var found = false;
    for (plan.rows) |row| {
        const line = row[0] orelse continue;
        if (std.mem.indexOf(u8, line, "platform_migrations_resume_idx") != null) {
            found = true;
            break;
        }
    }
    try std.testing.expect(found);
}
