// @generated by tools/codegen_migration.py — boilerplate is auto-generated.
// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate.
//
// Module: tests/integration/vld04_definition_semantic_verdict_test.zig
// Requirements: VLD-04
//
// Adds the semantic-validation verdict columns to process_definitions so the VLD-04 gate
// (src/validation/gate.zig) can record, per definition version, whether a clean CEL compile
// produced semantically_valid = true, which compiler version produced the verdict, when, and
// how many findings the last failed pass found. compiler_version is nullable: a NULL means
// "never validated or the stored version is stale", which drives VLD-04 AC3's re-verify-
// rather-than-trust rule. The columns are added with IF NOT EXISTS so the migration is
// idempotent across the public and per-tenant schema passes (process_definitions lives in
// every schema, per migration 004's PER_TENANT shadow convention). This migration only adds
// the columns; the gating orchestration that reads and writes them is Type E, per
// templates/lego-catalog.md's selection rules.
//
// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.

const std = @import("std");
const pg = @import("pg");
const helpers = @import("helpers.zig");

const Fixtures = struct {
    definition_name_value: []u8,
};

fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {
    // CUSTOM: realise per-test fixtures here (random string + the seeded DRAFT definition).
    const definition_name_value = try allocator.dupe(u8, "vld04-def-00000000-0000-0000-0000-000000000001");
    errdefer allocator.free(definition_name_value);

    // seed_definition — a DRAFT version with the empty graph; the verdict
    // columns default to the "never validated" starting state (AC1).
    try conn.exec(
        \\INSERT INTO process_definitions (name, version, status, graph, created_by)
        \\VALUES ($1, 'v1', 'DRAFT', '{"nodes":[],"edges":[]}'::jsonb, '00000000-0000-0000-0000-000000000001')
    ,
        &.{definition_name_value},
    );

    return Fixtures{
        .definition_name_value = definition_name_value,
    };
}

fn freeFixtures(allocator: std.mem.Allocator, fx: Fixtures) void {
    allocator.free(fx.definition_name_value);
}

test "vld04_definition_semantic_verdict: verdict_columns_exist_with_defaults" {
    // A freshly inserted definition version has semantically_valid = false, compiler_version NULL, validated_at NULL, validation_finding_count = 0 — the "never validated" starting state (AC1).
    // covers: VLD-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    var result = try h.conn.query(std.testing.allocator,
        "SELECT semantically_valid::text, compiler_version, validated_at, validation_finding_count FROM process_definitions WHERE name = $1",
        &.{fx.definition_name_value});
    defer result.deinit();

    // CUSTOM: assert result.rows.len == 1, semantically_valid == "false",
    // compiler_version IS NULL, validated_at IS NULL, validation_finding_count == "0".
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    const row = result.rows[0];
    try std.testing.expect(row.len >= 4);
    try std.testing.expectEqualStrings("false", row[0] orelse "");
    try std.testing.expect(row[1] == null);
    try std.testing.expect(row[2] == null);
    try std.testing.expectEqualStrings("0", row[3] orelse "");
}

test "vld04_definition_semantic_verdict: clean_pass_records_verdict_with_compiler_version" {
    // A clean validation pass persists semantically_valid = true with the compiler version that produced it (VLD-04 AC5 / AC3's comparison source).
    // covers: VLD-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "UPDATE process_definitions SET semantically_valid = true, compiler_version = $2, validated_at = now(), validation_finding_count = 0 WHERE name = $1",
        &.{ fx.definition_name_value, "vld-01-03-WF02-vld01-03-20260816" },
    );

    // CUSTOM: assert the row now reads semantically_valid = "true",
    // compiler_version = the constant, validated_at NOT NULL, finding count 0.
    var rows = try h.conn.query(std.testing.allocator,
        "SELECT semantically_valid::text, compiler_version, validated_at, validation_finding_count FROM process_definitions WHERE name = $1",
        &.{fx.definition_name_value});
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const row = rows.rows[0];
    try std.testing.expectEqualStrings("true", row[0] orelse "");
    try std.testing.expectEqualStrings("vld-01-03-WF02-vld01-03-20260816", row[1] orelse "");
    try std.testing.expect(row[2] != null);
    try std.testing.expectEqualStrings("0", row[3] orelse "");
}

test "vld04_definition_semantic_verdict: failed_pass_records_finding_count_and_stays_invalid" {
    // A validation failure persists semantically_valid = false with the finding count (AC1/AC5) — the definition is NOT marked valid on any finding.
    // covers: VLD-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "UPDATE process_definitions SET semantically_valid = true, compiler_version = 'old-version', validated_at = now(), validation_finding_count = 0 WHERE name = $1",
        &.{fx.definition_name_value},
    );

    try h.conn.exec(
        "UPDATE process_definitions SET semantically_valid = false, compiler_version = 'vld-01-03-WF02-vld01-03-20260816', validated_at = now(), validation_finding_count = 3 WHERE name = $1",
        &.{fx.definition_name_value},
    );

    // CUSTOM: assert semantically_valid = "false", compiler_version = the current
    // constant, validation_finding_count = "3" — the data DEFINITION_VALIDATION_FAILED
    // carries (AC5).
    var rows = try h.conn.query(std.testing.allocator,
        "SELECT semantically_valid::text, compiler_version, validation_finding_count FROM process_definitions WHERE name = $1",
        &.{fx.definition_name_value});
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    const row = rows.rows[0];
    try std.testing.expect(row.len >= 3);
    try std.testing.expectEqualStrings("false", row[0] orelse "");
    try std.testing.expectEqualStrings("vld-01-03-WF02-vld01-03-20260816", row[1] orelse "");
    try std.testing.expectEqualStrings("3", row[2] orelse "");
}

test "vld04_definition_semantic_verdict: stale_compiler_version_is_distinguishable" {
    // A verdict produced by an earlier compiler version is distinguishable from the current one by the stored compiler_version value, which is the AC3 re-verify trigger (VLD-04 AC3).
    // covers: VLD-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    try h.conn.exec(
        "UPDATE process_definitions SET semantically_valid = true, compiler_version = 'old-version', validated_at = now() WHERE name = $1",
        &.{fx.definition_name_value},
    );

    var result = try h.conn.query(std.testing.allocator,
        "SELECT compiler_version FROM process_definitions WHERE name = $1",
        &.{fx.definition_name_value});
    defer result.deinit();

    // CUSTOM: assert compiler_version == "old-version" (NOT the current constant),
    // so storedVerdictIsCurrent() compares it to COMPILER_VERSION and decides
    // re-verification is required.
    try std.testing.expectEqual(@as(usize, 1), result.rows.len);
    try std.testing.expectEqualStrings("old-version", result.rows[0][0] orelse "");
}

test "vld04_definition_semantic_verdict: finding_count_check_rejects_negative" {
    // validation_finding_count cannot go negative — CHECK constraint enforced.
    // covers: VLD-04
    var h = try helpers.TestHarness.init(std.testing.allocator);
    defer h.deinit();
    const fx = try setup(std.testing.allocator, &h.conn);
    defer freeFixtures(std.testing.allocator, fx);

    // CUSTOM: SAVEPOINT must precede the failing UPDATE (Postgres aborts the
    // transaction on error; only ROLLBACK TO SAVEPOINT recovers it).
    try h.conn.exec("SAVEPOINT before_neg", &.{});
    const result = h.conn.exec(
        "UPDATE process_definitions SET validation_finding_count = -1 WHERE name = $1",
        &.{fx.definition_name_value},
    );

    // CUSTOM: assert error.CheckConstraintViolation (SQLSTATE 23514) and that the
    // row's validation_finding_count is unchanged.
    try std.testing.expectError(error.ServerError, result);
    try h.conn.exec("ROLLBACK TO SAVEPOINT before_neg", &.{});

    var rows = try h.conn.query(std.testing.allocator,
        "SELECT validation_finding_count FROM process_definitions WHERE name = $1",
        &.{fx.definition_name_value});
    defer rows.deinit();
    try std.testing.expectEqual(@as(usize, 1), rows.rows.len);
    try std.testing.expectEqualStrings("0", rows.rows[0][0] orelse "");
}
