#!/usr/bin/env python3
"""
codegen_list_page.py — Generate `web/src/pages/<page_slug>/<PageName>.tsx`
from a Lego Type B parameter file.

Output is a React functional component that:
  - reads filter state via useState
  - fetches the list via useQuery and the queryKeys factory (NEVER an inline array)
  - renders a table with the spec'd columns
  - renders row actions (hidden by role, never disabled)
  - optionally renders a create form modal driven by useMutation

The output contains `{/* CUSTOM: ... */}` blocks for any custom UI logic.

See templates/specs/list-page.template.yaml for the input schema.

Usage:
  python3 tools/codegen_list_page.py templates/specs/myfeature.list-page.yaml
  python3 tools/codegen_list_page.py <spec> --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BANNER = (
    "/* @generated by tools/codegen_list_page.py — boilerplate is auto-generated.\n"
    "   Edit only inside `{/* CUSTOM: ... */}` blocks. Re-run codegen to refresh. */"
)


def load_yaml(path: Path):
    try:
        import yaml
    except ImportError as e:
        raise SystemExit("PyYAML is required. `pip install pyyaml`.") from e
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def emit_page(spec: dict) -> str:
    page_name = spec["page_name"]
    resource = spec["resource_name"]
    list_qk = spec["list_query_key"]
    api = spec.get("api", {})
    filters = spec.get("filters") or []
    columns = spec.get("columns") or []
    actions = spec.get("row_actions") or []
    cform = spec.get("create_form")
    purpose = (spec.get("purpose") or "").strip()

    lines: list[str] = []
    lines.append(BANNER)
    lines.append("import { useState } from 'react';")
    lines.append("import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';")
    lines.append("import { apiClient } from '../../api/client';")
    lines.append("import { queryKeys } from '../../api/queryKeys';")
    lines.append("import { useCurrentUserRole } from '../../auth/useCurrentUserRole';")
    lines.append("")
    lines.append("/**")
    lines.append(f" * {page_name}")
    if purpose:
        for ln in purpose.splitlines():
            lines.append(f" * {ln}")
    lines.append(" */")
    lines.append(f"export function {page_name}() {{")
    lines.append("    const queryClient = useQueryClient();")
    lines.append("    const role = useCurrentUserRole();")
    lines.append("")

    # Filter state
    for f in filters:
        default = repr(f.get("default", "")).replace("'", '"')
        lines.append(f"    const [{f['name']}, set{_pascal(f['name'])}] = useState<{_ts_type(f)}>({default});")
    lines.append("")

    # List query
    lines.append(f"    const listQuery = useQuery({{")
    lines.append(f"        queryKey: {list_qk}({_qk_params(filters)}),")
    lines.append(f"        queryFn: () => apiClient.get('{api.get('list_endpoint','/api/v1/'+resource+'s')}', {{")
    lines.append("            params: { " + ", ".join(f["name"] for f in filters) + " },")
    lines.append("        }).then(r => r.data),")
    lines.append("    });")
    lines.append("")

    # Row mutations
    for a in actions:
        if a["action"] == "archive":
            ep = api.get("delete_endpoint", f"/api/v1/{resource}s/:id")
            lines.append(f"    const archiveMutation = useMutation({{")
            lines.append(f"        mutationFn: (id: string) => apiClient.delete(`{ep.replace(':id','${id}')}`),")
            lines.append(f"        onSuccess: () => queryClient.invalidateQueries({{ queryKey: {list_qk}() }}),")
            lines.append("    });")
            lines.append("")

    # Create mutation
    if cform:
        ep = api.get("create_endpoint", f"/api/v1/{resource}s")
        invalidate_key = cform.get("on_success_invalidate", list_qk)
        lines.append("    const [showCreate, setShowCreate] = useState(false);")
        lines.append("    const createMutation = useMutation({")
        lines.append(f"        mutationFn: (payload: unknown) => apiClient.post('{ep}', payload).then(r => r.data),")
        lines.append("        onSuccess: () => {")
        lines.append(f"            queryClient.invalidateQueries({{ queryKey: {invalidate_key}() }});")
        lines.append("            setShowCreate(false);")
        lines.append("        },")
        lines.append("    });")
        lines.append("")

    # Render
    lines.append("    return (")
    lines.append("        <div className=\"page list-page\">")
    lines.append(f"            <h1>{page_name.replace('Page','')}</h1>")
    lines.append("")
    # Filters bar
    lines.append("            <form className=\"filters\" onSubmit={(e) => e.preventDefault()}>")
    for f in filters:
        lines.extend(_render_filter(f))
    lines.append("            </form>")
    lines.append("")

    # Create button
    if cform:
        lines.append("            {role === 'PLATFORM_ADMIN' && (")
        lines.append(f"                <button type=\"button\" onClick={{() => setShowCreate(true)}}>{cform.get('button_label','+ New')}</button>")
        lines.append("            )}")
        lines.append("")

    # Table
    lines.append("            {listQuery.isLoading && <p>Loading...</p>}")
    lines.append("            {listQuery.isError && <p>Failed to load.</p>}")
    lines.append("            {listQuery.data && (")
    lines.append("                <table className=\"data-table\">")
    lines.append("                    <thead>")
    lines.append("                        <tr>")
    for col in columns:
        lines.append(f"                            <th>{col['header']}</th>")
    if actions:
        lines.append("                            <th>Actions</th>")
    lines.append("                        </tr>")
    lines.append("                    </thead>")
    lines.append("                    <tbody>")
    lines.append("                        {listQuery.data.items?.map((row: any) => (")
    lines.append("                            <tr key={row.id}>")
    for col in columns:
        accessor = col["accessor"]
        fmt = col.get("format")
        cell = f"row.{accessor}"
        if fmt == "date":
            cell = f"new Date({cell}).toLocaleDateString()"
        lines.append(f"                                <td>{{{cell}}}</td>")
    if actions:
        lines.append("                                <td>")
        for a in actions:
            handler = "archiveMutation.mutate(row.id)" if a["action"] == "archive" else f"/* CUSTOM: action `{a['action']}` */"
            confirm = a.get("confirm")
            if confirm:
                handler = f"window.confirm({confirm!r}) && {handler}"
            req = a.get("requires_role")
            if req:
                lines.append(f"                                    {{role === '{req}' && (")
                lines.append(f"                                        <button type=\"button\" onClick={{() => {handler}}}>{a['label']}</button>")
                lines.append("                                    )}")
            else:
                lines.append(f"                                    <button type=\"button\" onClick={{() => {handler}}}>{a['label']}</button>")
        lines.append("                                </td>")
    lines.append("                            </tr>")
    lines.append("                        ))}")
    lines.append("                    </tbody>")
    lines.append("                </table>")
    lines.append("            )}")
    lines.append("")

    if cform:
        lines.append("            {showCreate && (")
        lines.append("                <div className=\"modal\">")
        lines.append("                    <form onSubmit={(e) => {")
        lines.append("                        e.preventDefault();")
        lines.append("                        const form = new FormData(e.currentTarget);")
        lines.append("                        createMutation.mutate(Object.fromEntries(form.entries()));")
        lines.append("                    }}>")
        for fld in cform.get("fields") or []:
            lines.extend(_render_create_field(fld))
        lines.append(f"                        <button type=\"submit\" disabled={{createMutation.isPending}}>{cform.get('submit_label','Create')}</button>")
        lines.append(f"                        <button type=\"button\" onClick={{() => setShowCreate(false)}}>Cancel</button>")
        lines.append("                    </form>")
        lines.append("                </div>")
        lines.append("            )}")
        lines.append("")

    lines.append("            {/* CUSTOM: extra UI (bulk actions, exports, etc.) below */}")
    lines.append("        </div>")
    lines.append("    );")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _pascal(s: str) -> str:
    return "".join(part.capitalize() for part in s.split("_"))


def _ts_type(f: dict) -> str:
    t = f["type"]
    if t in ("text", "select"):
        return "string"
    if t == "number":
        return "number"
    if t == "checkbox":
        return "boolean"
    return "string"


def _qk_params(filters: list[dict]) -> str:
    # Pass filters as a single options object so query key changes when filters change.
    if not filters:
        return ""
    return "{ " + ", ".join(f["name"] for f in filters) + " }"


def _render_filter(f: dict) -> list[str]:
    name = f["name"]
    label = f.get("label", name)
    indent = "                "
    if f["type"] == "select":
        opts = f.get("options") or []
        out = [
            f"{indent}<label>{label}",
            f"{indent}    <select value={{{name}}} onChange={{e => set{_pascal(name)}(e.target.value)}}>",
        ]
        for o in opts:
            out.append(f"{indent}        <option value={{'{o['value']}'}}>{o['label']}</option>")
        out += [f"{indent}    </select>", f"{indent}</label>"]
        return out
    if f["type"] == "number":
        return [
            f"{indent}<label>{label}",
            f"{indent}    <input type=\"number\" value={{{name}}} onChange={{e => set{_pascal(name)}(Number(e.target.value))}} />",
            f"{indent}</label>",
        ]
    placeholder = f.get("placeholder", "")
    return [
        f"{indent}<label>{label}",
        f"{indent}    <input type=\"text\" placeholder={{'{placeholder}'}} value={{{name}}} onChange={{e => set{_pascal(name)}(e.target.value)}} />",
        f"{indent}</label>",
    ]


def _render_create_field(fld: dict) -> list[str]:
    name = fld["name"]
    label = fld.get("label", name)
    required = "required" if fld.get("required") else ""
    indent = "                        "
    if fld["type"] == "textarea":
        return [
            f"{indent}<label>{label}",
            f"{indent}    <textarea name=\"{name}\" {required} />",
            f"{indent}</label>",
        ]
    if fld["type"] == "select":
        opts = fld.get("options") or []
        out = [
            f"{indent}<label>{label}",
            f"{indent}    <select name=\"{name}\" {required}>",
        ]
        for o in opts:
            out.append(f"{indent}        <option value=\"{o['value']}\">{o['label']}</option>")
        out += [f"{indent}    </select>", f"{indent}</label>"]
        return out
    return [
        f"{indent}<label>{label}",
        f"{indent}    <input type=\"text\" name=\"{name}\" {required} />",
        f"{indent}</label>",
    ]


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("spec", type=Path)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--output-root", type=Path, default=REPO_ROOT / "web" / "src" / "pages")
    args = p.parse_args(argv)

    spec_path = args.spec if args.spec.is_absolute() else (REPO_ROOT / args.spec).resolve()
    if not spec_path.exists():
        print(f"spec not found: {spec_path}", file=sys.stderr)
        return 2

    spec = load_yaml(spec_path)
    if not isinstance(spec, dict) or "page_name" not in spec:
        print("spec must define `page_name`", file=sys.stderr)
        return 2

    text = emit_page(spec)

    if args.dry_run:
        print(text)
        return 0

    slug = spec.get("page_slug", spec["page_name"].lower())
    out_dir = args.output_root / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{spec['page_name']}.tsx"
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
