#!/usr/bin/env python3
"""
codegen_migration.py — Generate `migrations/<NNN>_<name>.sql` and
`tests/integration/<name>_test.zig` from a Lego Type C parameter file.

See templates/migration.schema.md for the full spec format.

Usage:
  python3 tools/codegen_migration.py templates/specs/myfeature.migration.yaml
  python3 tools/codegen_migration.py <spec> --dry-run
  python3 tools/codegen_migration.py <spec> --sql-only
  python3 tools/codegen_migration.py <spec> --test-only

Idempotent: re-running over the same YAML reproduces the same output.
Generated files contain `-- CUSTOM:` / `// CUSTOM:` blocks; implementers
edit ONLY those blocks. If boilerplate is wrong, fix the template.
"""
from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_BANNER_SQL = "-- @generated by tools/codegen_migration.py — do not edit boilerplate, edit the YAML."
GENERATED_BANNER_ZIG = "// @generated by tools/codegen_migration.py — boilerplate is auto-generated.\n// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh boilerplate."


def load_yaml(path: Path):
    try:
        import yaml
    except ImportError as e:
        raise SystemExit("PyYAML is required. `pip install pyyaml`.") from e
    return yaml.safe_load(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# SQL emission
# ---------------------------------------------------------------------------
def emit_sql(spec: dict) -> str:
    number = spec["migration_number"]
    name = spec["name"]
    purpose = spec.get("purpose", "").rstrip()
    requirement_ids = spec.get("requirement_ids", [])

    header = [
        GENERATED_BANNER_SQL,
        f"-- {number:03d}_{name}.sql",
        f"-- Requirements: {', '.join(requirement_ids) if requirement_ids else '(none listed)'}",
        "--",
    ]
    for ln in purpose.splitlines():
        header.append(f"-- {ln}" if ln else "--")

    parts = ["\n".join(header), ""]

    for table in spec.get("tables", []):
        mode = table.get("mode", "create")
        tname = table["name"]
        if mode == "create":
            parts.append(_emit_create_table(table))
        elif mode == "alter":
            parts.append(_emit_alter_table(table))
        for idx in table.get("indexes") or []:
            parts.append(_emit_index(tname, idx))

    return "\n\n".join(p for p in parts if p) + "\n"


def _emit_create_table(table: dict) -> str:
    tname = table["name"]
    cols = []
    for c in table.get("columns") or []:
        cols.append(_emit_column(c))
    for cn in table.get("constraints") or []:
        cline = _emit_constraint(cn)
        if cline:
            cols.append(cline)
    inside = ",\n    ".join(cols)
    return f"CREATE TABLE IF NOT EXISTS {tname} (\n    {inside}\n);"


def _emit_alter_table(table: dict) -> str:
    tname = table["name"]
    lines = [f"ALTER TABLE {tname}"]
    parts = []
    for c in table.get("add_columns") or []:
        parts.append(f"    ADD COLUMN IF NOT EXISTS {_emit_column(c, in_create=False)}")
    for cn in table.get("add_constraints") or []:
        constraint_body = _emit_constraint(cn)
        if constraint_body:
            parts.append(f"    ADD {constraint_body}")
    if not parts:
        return ""
    return lines[0] + "\n" + ",\n".join(parts) + ";"


def _emit_column(c: dict, in_create: bool = True) -> str:
    parts = [c["name"], c["type"]]
    if c.get("pk"):
        parts.append("PRIMARY KEY")
    if c.get("not_null"):
        parts.append("NOT NULL")
    if c.get("default") is not None:
        parts.append(f"DEFAULT {c['default']}")
    if c.get("check"):
        parts.append(f"CHECK ({c['check']})")
    if c.get("fk"):
        parts.append(f"REFERENCES {c['fk']}")
    return " ".join(parts)


def _emit_constraint(cn: dict) -> str:
    kind = cn.get("kind")
    name_clause = f"CONSTRAINT {cn['name']} " if cn.get("name") else ""
    if kind == "unique":
        return f"{name_clause}UNIQUE ({', '.join(cn['columns'])})"
    if kind == "check":
        return f"{name_clause}CHECK ({cn['expression']})"
    if kind == "foreign_key":
        return f"{name_clause}FOREIGN KEY ({', '.join(cn['columns'])}) REFERENCES {cn['references']}"
    if kind == "exclude":
        return f"{name_clause}EXCLUDE {cn.get('using', 'USING gist')} ({cn['expression']})"
    return ""


def _emit_index(table: str, idx: dict) -> str:
    name = idx["name"]
    cols = ", ".join(idx["columns"])
    unique = "UNIQUE " if idx.get("unique") else ""
    where = f" WHERE {idx['where']}" if idx.get("where") else ""
    return f"CREATE {unique}INDEX IF NOT EXISTS {name} ON {table} ({cols}){where};"


# ---------------------------------------------------------------------------
# Zig integration test emission
# ---------------------------------------------------------------------------
def emit_test(spec: dict) -> str:
    name = spec["name"]
    requirement_ids = spec.get("requirement_ids", [])
    purpose = spec.get("purpose", "").strip()

    out: list[str] = []
    out.append(GENERATED_BANNER_ZIG)
    out.append(f"//")
    out.append(f"// Module: tests/integration/{name}_test.zig")
    out.append(f"// Requirements: {', '.join(requirement_ids)}")
    out.append("//")
    if purpose:
        for ln in textwrap.wrap(purpose, 90):
            out.append(f"// {ln}")
        out.append("//")
    out.append("// BPM_TEST_DB_URL must be set; the test connects to a real PostgreSQL.")
    out.append("")
    out.append('const std = @import("std");')
    out.append('const pg = @import("pg");')
    out.append('const helpers = @import("helpers.zig");')
    out.append("")
    out.append("const Fixtures = struct {")
    for f in spec.get("fixtures") or []:
        if f["kind"] == "uuid":
            out.append(f"    {f['name']}: [16]u8,")
        elif f["kind"] == "random_string":
            out.append(f"    {f['name']}: []u8,")
        elif f["kind"] == "timestamp_now":
            out.append(f"    {f['name']}: i64,")
        elif f["kind"] in ("sql_setup", "sql_literal"):
            # values are realised at setup time; no struct field needed
            continue
    out.append("};")
    out.append("")
    out.append("fn setup(allocator: std.mem.Allocator, conn: *pg.Conn) !Fixtures {")
    out.append("    _ = conn;")
    out.append("    _ = allocator;")
    out.append("    // CUSTOM: realise per-test fixtures here (UUIDs, random strings, seed SQL).")
    out.append("    return Fixtures{")
    for f in spec.get("fixtures") or []:
        if f["kind"] == "uuid":
            out.append(f"        .{f['name']} = std.crypto.random.bytes(16),")
        elif f["kind"] == "random_string":
            out.append(f'        .{f["name"]} = try allocator.dupe(u8, "fx_{f["name"]}_REPLACE"),')
        elif f["kind"] == "timestamp_now":
            out.append(f"        .{f['name']} = std.time.timestamp(),")
    out.append("    };")
    out.append("}")
    out.append("")

    for tc in spec.get("test_cases") or []:
        out.append(_emit_test_block(name, tc))
        out.append("")

    return "\n".join(out)


def _emit_test_block(module_name: str, tc: dict) -> str:
    title = f'{module_name}: {tc["name"]}'
    desc = tc.get("description", "").strip()
    req = tc.get("requirement_ref", "")
    arrange = (tc.get("arrange") or "").strip()
    act = (tc.get("act") or "").strip()
    assertions = (tc.get("assertions") or "").rstrip()

    lines = [f'test "{title}" {{']
    if desc:
        lines.append(f"    // {desc}")
    if req:
        lines.append(f"    // covers: {req}")
    lines.append("    var h = try helpers.TestHarness.init(std.testing.allocator);")
    lines.append("    defer h.deinit();")
    lines.append("    const fx = try setup(std.testing.allocator, h.conn);")
    lines.append("    _ = fx;")
    if arrange:
        lines.append("")
        for ln in arrange.splitlines():
            lines.append(f"    {ln}")
    if act:
        lines.append("")
        for ln in act.splitlines():
            lines.append(f"    {ln}")
    lines.append("")
    lines.append("    // CUSTOM: assertions for this test case — handwritten by the implementer.")
    if assertions and "CUSTOM" not in assertions:
        # We never emit the implementer's draft assertions verbatim (lint Y134
        # forbids them in the YAML). If they slip through, demote to a comment.
        for ln in assertions.splitlines():
            lines.append(f"    // {ln}")
    elif assertions:
        for ln in assertions.splitlines():
            lines.append(f"    {ln}")
    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("spec", type=Path)
    p.add_argument("--dry-run", action="store_true", help="print to stdout, do not write")
    p.add_argument("--sql-only", action="store_true")
    p.add_argument("--test-only", action="store_true")
    p.add_argument("--output-dir-sql", type=Path, default=REPO_ROOT / "migrations")
    p.add_argument("--output-dir-test", type=Path, default=REPO_ROOT / "tests" / "integration")
    args = p.parse_args(argv)

    spec_path = args.spec if args.spec.is_absolute() else (REPO_ROOT / args.spec).resolve()
    if not spec_path.exists():
        print(f"spec not found: {spec_path}", file=sys.stderr)
        return 2

    spec = load_yaml(spec_path)
    if not isinstance(spec, dict):
        print("YAML root must be a mapping", file=sys.stderr)
        return 2

    number = spec.get("migration_number")
    name = spec.get("name")
    if not isinstance(number, int) or not isinstance(name, str):
        print("spec must define `migration_number` (int) and `name` (str)", file=sys.stderr)
        return 2

    write_sql = not args.test_only
    write_test = not args.sql_only

    sql_text = emit_sql(spec) if write_sql else ""
    test_text = emit_test(spec) if write_test else ""

    if args.dry_run:
        if write_sql:
            print(f"--- {number:03d}_{name}.sql ---\n{sql_text}")
        if write_test:
            print(f"--- {name}_test.zig ---\n{test_text}")
        return 0

    if write_sql:
        args.output_dir_sql.mkdir(parents=True, exist_ok=True)
        sql_path = args.output_dir_sql / f"{number:03d}_{name}.sql"
        sql_path.write_text(sql_text, encoding="utf-8")
        print(f"wrote {sql_path.relative_to(REPO_ROOT)}")

    if write_test:
        args.output_dir_test.mkdir(parents=True, exist_ok=True)
        test_path = args.output_dir_test / f"{name}_test.zig"
        test_path.write_text(test_text, encoding="utf-8")
        print(f"wrote {test_path.relative_to(REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
