#!/usr/bin/env python3
"""
codegen_error_mapper.py — Generate a `errorToResponse()` function from a Zig
error set definition.

Each HTTP handler module in `src/api/routes/*.zig` re-writes the same error
→ HTTP-status switch. This tool reads a Zig file, finds error set definitions
of the shape

    pub const FooError = error {
        Bar,
        Baz,
        Qux,
    };

and emits a companion `_errors.zig` file with a strongly-typed mapping:

    pub fn fooErrorToResponse(allocator: std.mem.Allocator, err: FooError) HandlerResult {
        return switch (err) {
            error.Bar => errorResult(allocator, 422, "validation failed"),
            error.Baz => errorResult(allocator, 409, "conflict"),
            error.Qux => errorResult(allocator, 500, "internal server error"),
        };
    }

The generated file contains `CUSTOM:` blocks where the implementer assigns the
status code + message for each error variant. The codegen attempts to guess
based on the variant name (`NotFound` → 404, `Forbidden` → 403, etc.); guesses
are flagged with a `// TODO(codegen):` comment for human review.

Usage:
  python3 tools/codegen_error_mapper.py src/identity/store.zig
  python3 tools/codegen_error_mapper.py src/identity/store.zig --dry-run
  python3 tools/codegen_error_mapper.py src/identity/store.zig --output src/api/routes/identity_errors.zig
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

ERROR_SET_RE = re.compile(
    r"pub\s+const\s+([A-Za-z_][A-Za-z0-9_]*Error)\s*=\s*error\s*\{([^}]*)\}",
    re.DOTALL,
)
VARIANT_RE = re.compile(r"([A-Z][A-Za-z0-9_]*)")

# Heuristic mappings — variant name substring → (HTTP status, message)
STATUS_HEURISTICS = [
    ("NotFound",        404, "not found"),
    ("Missing",         404, "not found"),
    ("AlreadyExists",   409, "already exists"),
    ("Duplicate",       409, "conflict"),
    ("Conflict",        409, "conflict"),
    ("Forbidden",       403, "forbidden"),
    ("Unauthorised",    401, "unauthorized"),
    ("Unauthorized",    401, "unauthorized"),
    ("InvalidInput",    422, "validation failed"),
    ("Invalid",         422, "validation failed"),
    ("Reserved",        422, "reserved name"),
    ("Validation",      422, "validation failed"),
    ("PoolExhausted",   503, "service unavailable"),
    ("Unavailable",     503, "service unavailable"),
    ("Timeout",         504, "upstream timeout"),
    ("RateLimit",       429, "rate limited"),
    ("TooLarge",        413, "payload too large"),
]


def guess_status(variant: str) -> tuple[int, str, bool]:
    """Return (status_code, message, was_guessed)."""
    for needle, code, msg in STATUS_HEURISTICS:
        if needle in variant:
            return code, msg, True
    return 500, "internal server error", True


def parse_error_sets(source: str) -> list[tuple[str, list[str]]]:
    out: list[tuple[str, list[str]]] = []
    for m in ERROR_SET_RE.finditer(source):
        name = m.group(1)
        body = m.group(2)
        # Strip line comments and split on commas/newlines, pick identifiers
        stripped = re.sub(r"//[^\n]*", "", body)
        variants = []
        for line in re.split(r"[,\n]", stripped):
            tok = line.strip()
            if not tok:
                continue
            mv = VARIANT_RE.match(tok)
            if mv:
                variants.append(mv.group(1))
        if variants:
            out.append((name, variants))
    return out


def to_camel(name: str) -> str:
    return name[:1].lower() + name[1:] if name else name


def emit_mapper(source_path: Path, error_sets: list[tuple[str, list[str]]]) -> str:
    out = [
        "// @generated by tools/codegen_error_mapper.py",
        f"// Source: {source_path.as_posix()}",
        "// Edit only inside `// CUSTOM:` blocks; re-run codegen to refresh.",
        "",
        'const std = @import("std");',
        f'const source = @import("{source_path.name}");',
        "",
        "/// Result returned by each handler — matches src/api/routes/definitions.zig.",
        "pub const HandlerResult = struct {",
        "    status_code: u16,",
        "    body: []const u8,",
        "};",
        "",
        "fn errorResult(allocator: std.mem.Allocator, status: u16, message: []const u8) HandlerResult {",
        "    const body = std.fmt.allocPrint(allocator,",
        '        "{{\\"error\\":\\"{s}\\"}}",',
        "        .{message},",
        "    ) catch \"\";",
        "    return .{ .status_code = status, .body = body };",
        "}",
        "",
    ]

    for set_name, variants in error_sets:
        fn_name = to_camel(set_name) + "ToResponse"
        out.append(f"/// HTTP-response mapping for {set_name}.")
        out.append(f"/// CUSTOM: review each row; codegen guesses based on variant name and may be wrong.")
        out.append(f"pub fn {fn_name}(allocator: std.mem.Allocator, err: source.{set_name}) HandlerResult {{")
        out.append("    return switch (err) {")
        for v in variants:
            code, msg, guessed = guess_status(v)
            tag = "  // TODO(codegen): verify status/message" if guessed else ""
            out.append(f'        error.{v} => errorResult(allocator, {code}, "{msg}"),{tag}')
        out.append("    };")
        out.append("}")
        out.append("")

    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("source", type=Path, help="Zig source file containing one or more `pub const FooError = error { ... };`")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--output", type=Path, help="output path (default: alongside source with _errors.zig suffix)")
    args = p.parse_args(argv)

    src_path = args.source if args.source.is_absolute() else (REPO_ROOT / args.source).resolve()
    if not src_path.exists():
        print(f"source not found: {src_path}", file=sys.stderr)
        return 2

    source = src_path.read_text(encoding="utf-8")
    error_sets = parse_error_sets(source)
    if not error_sets:
        print(f"no `pub const ...Error = error {{ ... }};` blocks found in {src_path}", file=sys.stderr)
        return 1

    text = emit_mapper(src_path.relative_to(src_path.parent), error_sets)

    if args.dry_run:
        print(text)
        return 0

    out_path = args.output if args.output else src_path.with_name(src_path.stem + "_errors.zig")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    try:
        rel = out_path.relative_to(REPO_ROOT)
    except ValueError:
        rel = out_path
    print(f"wrote {rel} — {sum(len(v) for _, v in error_sets)} error variants across {len(error_sets)} sets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
