#!/usr/bin/env python3
"""
codegen_react_flow_node.py — Generate
`web/src/components/canvas/nodes/<ComponentName>.tsx` from a Lego Type D
parameter file.

Output is a typed React Flow custom node component with:
  - the standard CanvasNodeData prop shape
  - optional validation-error badge (top-right red bubble)
  - inline SVG icon + label/subtitle rows
  - one <Handle> per entry in `handles`

The output contains a `{/* CUSTOM: ... */}` block for any extra UI logic.

See templates/specs/react-flow-node.template.yaml for the input schema.

Usage:
  python3 tools/codegen_react_flow_node.py templates/specs/myfeature.react-flow-node.yaml
  python3 tools/codegen_react_flow_node.py <spec> --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BANNER = (
    "/* @generated by tools/codegen_react_flow_node.py — boilerplate is auto-generated.\n"
    "   Edit only inside `{/* CUSTOM: ... */}` blocks. Re-run codegen to refresh. */"
)


def load_yaml(path: Path):
    try:
        import yaml
    except ImportError as e:
        raise SystemExit("PyYAML is required. `pip install pyyaml`.") from e
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _border_radius(shape: str) -> str:
    if shape == "circle":
        return "'50%'"
    if shape == "rounded":
        return "16"
    if shape == "diamond":
        # Diamond is a rotated square — radius 0 + transform rotate
        return "0"
    return "8"


def _shape_transform(shape: str) -> str | None:
    if shape == "diamond":
        return "'rotate(45deg)'"
    return None


def _position_enum(p: str) -> str:
    return {
        "top": "Position.Top",
        "right": "Position.Right",
        "bottom": "Position.Bottom",
        "left": "Position.Left",
    }.get(p, "Position.Top")


def emit_node(spec: dict) -> str:
    name = spec["component_name"]
    shape = spec.get("shape", "rectangle")
    width = spec.get("width", 180)
    min_h = spec.get("min_height", 72)
    border_var = spec.get("border_color_var", "--color-brand-500")
    border_fb = spec.get("border_color_fallback", "#339af0")
    bg_var = spec.get("background_color_var", "--color-neutral-0")
    bg_fb = spec.get("background_color_fallback", "#ffffff")
    label_field = spec.get("label_field", "name")
    subtitle = spec.get("subtitle", "")
    validation_field = spec.get("validation_field", "validationError")
    icon_svg = (spec.get("icon_svg") or "").strip()
    handles = spec.get("handles") or []
    purpose = (spec.get("purpose") or "").strip()

    radius = _border_radius(shape)
    transform = _shape_transform(shape)

    lines: list[str] = []
    lines.append(BANNER)
    lines.append("import { Handle, Position, type NodeProps, type Node } from '@xyflow/react'")
    lines.append("import type { CanvasNodeData } from '@/utils/canvas/graphToFlow'")
    lines.append("")
    lines.append("/**")
    lines.append(f" * {name}")
    if purpose:
        for ln in purpose.splitlines():
            lines.append(f" * {ln}")
    lines.append(" */")
    lines.append(f"export default function {name}({{ data, selected }}: NodeProps<Node<CanvasNodeData>>) {{")
    lines.append("  return (")
    lines.append("    <div")
    lines.append(f'      className="{spec["node_kind"].replace("_","-")}-node"')
    lines.append("      style={{")
    lines.append(f"        width: {width},")
    lines.append(f"        minHeight: {min_h},")
    lines.append(f"        borderRadius: {radius},")
    lines.append(f"        border: '1.5px solid var({border_var}, {border_fb})',")
    lines.append(f"        background: 'var({bg_var}, {bg_fb})',")
    lines.append("        padding: '8px 12px',")
    lines.append("        display: 'flex',")
    lines.append("        flexDirection: 'column',")
    lines.append("        gap: 2,")
    lines.append("        position: 'relative',")
    lines.append("        boxShadow: selected ? '0 0 0 3px rgba(34,139,230,0.2)' : undefined,")
    lines.append("        cursor: 'pointer',")
    if transform:
        lines.append(f"        transform: {transform},")
    lines.append("      }}")
    lines.append("    >")

    # Validation badge
    if validation_field:
        lines.append(f"      {{data.{validation_field} && (")
        lines.append("        <div")
        lines.append("          style={{")
        lines.append("            position: 'absolute',")
        lines.append("            top: -6,")
        lines.append("            right: -6,")
        lines.append("            width: 16,")
        lines.append("            height: 16,")
        lines.append("            borderRadius: '50%',")
        lines.append("            background: 'var(--color-error, #fa5252)',")
        lines.append("            display: 'flex',")
        lines.append("            alignItems: 'center',")
        lines.append("            justifyContent: 'center',")
        lines.append("            fontSize: 10,")
        lines.append("            color: '#fff',")
        lines.append("            fontWeight: 'bold',")
        lines.append("          }}")
        lines.append(f"          title={{data.{validation_field}}}")
        lines.append("        >")
        lines.append("          !")
        lines.append("        </div>")
        lines.append("      )}")

    # Icon + label row
    lines.append("      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>")
    if icon_svg:
        for ln in icon_svg.splitlines():
            lines.append(f"        {ln}")
    lines.append("        <span")
    lines.append("          style={{")
    lines.append("            fontWeight: 600,")
    lines.append("            fontSize: 'var(--text-sm, 0.875rem)',")
    lines.append("            color: 'var(--text-primary, #212529)',")
    lines.append("            overflow: 'hidden',")
    lines.append("            textOverflow: 'ellipsis',")
    lines.append("            whiteSpace: 'nowrap',")
    lines.append(f"            maxWidth: {max(0, width - 50)},")
    lines.append("          }}")
    lines.append("        >")
    lines.append(f"          {{data.{label_field} || '{name.replace('Node','')}'}}")
    lines.append("        </span>")
    lines.append("      </div>")

    # Subtitle row
    if subtitle:
        lines.append("      <span")
        lines.append("        style={{")
        lines.append("          fontSize: 'var(--text-xs, 0.75rem)',")
        lines.append("          color: 'var(--text-secondary, #6c757d)',")
        lines.append("          marginLeft: 24,")
        lines.append("        }}")
        lines.append("      >")
        lines.append(f"        {subtitle}")
        lines.append("      </span>")

    lines.append("")
    lines.append("      {/* CUSTOM: additional badges, counters, or status indicators */}")
    lines.append("")

    # Handles
    for h in handles:
        pos = _position_enum(h.get("position", "top"))
        hid = h.get("id", h.get("type", "default"))
        htype = h.get("type", "source")
        lines.append(f'      <Handle id="{hid}" type="{htype}" position={{{pos}}} />')

    lines.append("    </div>")
    lines.append("  )")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("spec", type=Path)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "web" / "src" / "components" / "canvas" / "nodes",
    )
    args = p.parse_args(argv)

    spec_path = args.spec if args.spec.is_absolute() else (REPO_ROOT / args.spec).resolve()
    if not spec_path.exists():
        print(f"spec not found: {spec_path}", file=sys.stderr)
        return 2

    spec = load_yaml(spec_path)
    if not isinstance(spec, dict) or "component_name" not in spec:
        print("spec must define `component_name`", file=sys.stderr)
        return 2

    text = emit_node(spec)

    if args.dry_run:
        print(text)
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    out_path = args.output_dir / f"{spec['component_name']}.tsx"
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
