#!/usr/bin/env python3
"""
codegen_crud_endpoint.py — Generate `src/api/routes/<resource>.zig` from a
Lego Type A parameter file (`templates/specs/<name>.crud-endpoint.yaml`).

Output contains:
  - module-level imports
  - body / query-parameter struct stubs
  - one `pub fn handle<Verb>(...)` per endpoint, with a routed error switch
  - one `// CUSTOM: business validation` block per handler
  - a routing snippet (commented) at the bottom to paste into router.zig

See templates/specs/crud-endpoint.template.yaml for the input schema.

Usage:
  python3 tools/codegen_crud_endpoint.py templates/specs/myfeature.crud-endpoint.yaml
  python3 tools/codegen_crud_endpoint.py <spec> --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

BANNER = (
    "// @generated by tools/codegen_crud_endpoint.py — boilerplate is auto-generated.\n"
    "// Edit only inside `// CUSTOM:` blocks. Re-run codegen to refresh."
)

OP_TO_VERB = {
    "create": "Create",
    "read":   "GetById",
    "list":   "List",
    "update": "Update",
    "delete": "Delete",
    "custom": "Custom",
}


def load_yaml(path: Path):
    try:
        import yaml
    except ImportError as e:
        raise SystemExit("PyYAML is required. `pip install pyyaml`.") from e
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def emit_file(spec: dict) -> str:
    resource = spec["resource_name"]
    store_module = spec.get("store_module", "")
    store_struct = spec.get("store_struct", f"{resource}_store.Store")
    requirement_ids = spec.get("requirement_ids", [])
    purpose = (spec.get("purpose") or "").strip()
    default_error_map = spec.get("default_error_map") or {}

    lines: list[str] = []
    lines.append(BANNER)
    lines.append("//")
    lines.append(f"//! HTTP route handlers for {resource} (Lego Type A).")
    lines.append(f"//! Requirements: {', '.join(requirement_ids) if requirement_ids else '(none)'}")
    if purpose:
        for ln in purpose.splitlines():
            lines.append(f"//! {ln}" if ln else "//!")
    lines.append("")
    lines.append('const std = @import("std");')
    if store_module:
        # Drop "src/" prefix and ".zig" suffix to form an @import path relative to caller
        rel = store_module
        if rel.startswith("src/"):
            rel = rel[4:]
        lines.append(f'const {resource}_store = @import("../../{rel}");')
    lines.append("")
    lines.append("pub const HandlerResult = struct {")
    lines.append("    status_code: u16,")
    lines.append("    body: []const u8,")
    lines.append("};")
    lines.append("")
    lines.append("fn errorResult(allocator: std.mem.Allocator, status: u16, message: []const u8) HandlerResult {")
    lines.append("    const body = std.fmt.allocPrint(allocator,")
    lines.append('        "{{\\"error\\":\\"{s}\\"}}",')
    lines.append("        .{message},")
    lines.append("    ) catch \"\";")
    lines.append("    return .{ .status_code = status, .body = body };")
    lines.append("}")
    lines.append("")

    # Body-type structs
    seen_body_types: set[str] = set()
    for ep in spec.get("endpoints") or []:
        bt = ep.get("body_type")
        if not bt or bt in seen_body_types:
            continue
        seen_body_types.add(bt)
        lines.append(f"pub const {bt} = struct {{")
        for f in ep.get("body_fields") or []:
            lines.append(f"    {f['name']}: {f['type']},")
        lines.append("};")
        lines.append("")

    # Handlers
    for ep in spec.get("endpoints") or []:
        lines.extend(_emit_handler(resource, store_struct, ep, default_error_map))
        lines.append("")

    # Routing snippet (commented)
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Routing snippet — paste into src/api/router.zig (router wiring is manual).")
    lines.append("// ---------------------------------------------------------------------------")
    for ep in spec.get("endpoints") or []:
        verb = OP_TO_VERB.get(ep.get("operation", "custom"), "Custom")
        lines.append(f"//   {ep['method']:6s} {ep['path']:42s} → handle{verb}")
    return "\n".join(lines) + "\n"


def _emit_handler(resource: str, store_struct: str, ep: dict, default_error_map: dict) -> list[str]:
    op = ep.get("operation", "custom")
    verb = OP_TO_VERB.get(op, "Custom")
    method = ep.get("method", "GET")
    path = ep.get("path", "")
    success_status = ep.get("success_status", 200)
    error_map = {**default_error_map, **(ep.get("error_map") or {})}
    actor_required = ep.get("actor_required", False)

    out: list[str] = []
    out.append(f"/// {method} {path}")
    out.append("///")
    out.append(f"/// Success: HTTP {success_status}.")
    for err, status in error_map.items():
        out.append(f"/// {err}: HTTP {status}.")

    # Function signature
    params = [f"store: *{store_struct}", "allocator: std.mem.Allocator"]
    if ep.get("path_param"):
        ptype = ep.get("path_param_type", "[]const u8")
        if ptype == "uuid":
            params.append(f"{ep['path_param']}_str: []const u8")
        else:
            params.append(f"{ep['path_param']}: {ptype}")
    if ep.get("body_type"):
        params.append(f"body: {ep['body_type']}")
    for q in ep.get("query_params") or []:
        params.append(f"{q['name']}: {q['type']}")
    if actor_required:
        params.append("actor_id: [16]u8")
    params_str = ", ".join(params)

    out.append(f"pub fn handle{verb}({params_str}) HandlerResult {{")

    if ep.get("path_param") and ep.get("path_param_type") == "uuid":
        out.append(f"    const {ep['path_param']} = parseUuid({ep['path_param']}_str) catch {{")
        out.append('        return errorResult(allocator, 422, "invalid id format");')
        out.append("    };")

    out.append("    // CUSTOM: pre-store validation goes here (input shape, RBAC, etc.).")

    # Store call
    method_call = ep.get("store_method", f"store.{op}")
    call_args = []
    if ep.get("path_param") and ep.get("path_param_type") == "uuid":
        call_args.append(ep["path_param"])
    elif ep.get("path_param"):
        call_args.append(ep["path_param"])
    if ep.get("body_type"):
        call_args.append("body")
    for q in ep.get("query_params") or []:
        call_args.append(q["name"])
    if actor_required:
        call_args.append("actor_id")
    call_args.insert(0, "allocator")
    call = f"{method_call}({', '.join(call_args)})"

    out.append("")
    out.append(f"    const result = {call} catch |err| switch (err) {{")
    for err_name, status in error_map.items():
        msg = _message_for_status(err_name, status)
        out.append(f'        error.{err_name} => return errorResult(allocator, {status}, "{msg}"),')
    out.append('        else => return errorResult(allocator, 500, "internal server error"),')
    out.append("    };")
    out.append("")
    out.append("    // CUSTOM: serialise `result` into JSON. Replace the body below.")
    out.append('    const body = std.fmt.allocPrint(allocator, "{{}}", .{}) catch "";')
    out.append("    _ = result;")
    out.append(f"    return .{{ .status_code = {success_status}, .body = body }};")
    out.append("}")
    return out


def _message_for_status(err_name: str, status: int) -> str:
    fallback = {
        400: "bad request",
        401: "unauthorized",
        403: "forbidden",
        404: "not found",
        409: "conflict",
        422: "validation failed",
        429: "rate limited",
        500: "internal server error",
        503: "service unavailable",
    }
    return fallback.get(status, err_name)


# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    p.add_argument("spec", type=Path)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--output-dir", type=Path, default=REPO_ROOT / "src" / "api" / "routes")
    args = p.parse_args(argv)

    spec_path = args.spec if args.spec.is_absolute() else (REPO_ROOT / args.spec).resolve()
    if not spec_path.exists():
        print(f"spec not found: {spec_path}", file=sys.stderr)
        return 2

    spec = load_yaml(spec_path)
    if not isinstance(spec, dict) or "resource_name" not in spec:
        print("spec must define `resource_name`", file=sys.stderr)
        return 2

    text = emit_file(spec)

    if args.dry_run:
        print(text)
        return 0

    args.output_dir.mkdir(parents=True, exist_ok=True)
    out_path = args.output_dir / f"{spec['resource_name']}.zig"
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path.relative_to(REPO_ROOT)} — {len(spec.get('endpoints') or [])} endpoint(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
