/* @generated by tools/codegen_list_page.py — boilerplate is auto-generated.
   Edit only inside CUSTOM blocks. Re-run codegen to refresh. */
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Navigate, useNavigate, Link } from 'react-router-dom'
import { useAuth } from '@/auth/AuthContext'
import { client } from '@/api/client'
import { queryKeys } from '@/api/queryKeys'
import type { TenantListResponse } from '@/api/tenants'

/**
 * TenantsPage
 * PLATFORM_ADMIN-only paginated list of all registered tenants. Displays slug,
 * display name, IDP realm, status, and creation date. Provides per-row Edit
 * navigation (TM-03) and a navigation button to the existing onboarding route
 * (TM-02). Non-PLATFORM_ADMIN users must be redirected to /instances on page
 * load — enforce in the role-gate CUSTOM block.
 */

const PAGE_SIZE = 20

export default function TenantsPage() {
  const { session } = useAuth()
  const navigate = useNavigate()

  const [search, setSearch] = useState<string>('')
  const [offset, setOffset] = useState<number>(0)

  const listParams = { search: search || undefined, limit: PAGE_SIZE, offset }

  const listQuery = useQuery({
    queryKey: queryKeys.admin.tenants(listParams),
    queryFn: () =>
      client.get<TenantListResponse>('/api/v1/tenants', listParams as Record<string, unknown>),
  })

  // CUSTOM: role-gate
  if (!session?.roles.includes('PLATFORM_ADMIN')) {
    return <Navigate to="/instances" replace />
  }

  const data = listQuery.data
  const total = data?.total ?? 0
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))
  const currentPage = Math.floor(offset / PAGE_SIZE) + 1

  function handleSearchChange(value: string) {
    setSearch(value)
    setOffset(0)
  }

  return (
    <div data-testid="tenants-page" style={{ padding: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h1 style={{ margin: 0 }}>Tenants</h1>
        {/* CUSTOM: add-tenant-link */}
        <Link
          to="/admin/onboarding/new"
          data-testid="register-new-tenant-btn"
          style={{
            display: 'inline-block',
            padding: '.45rem 1rem',
            background: '#2563eb',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            textDecoration: 'none',
            fontSize: '.9rem',
            fontWeight: 600,
          }}
        >
          + Add Tenant
        </Link>
      </div>

      <form
        style={{ marginBottom: '1rem' }}
        onSubmit={(e) => e.preventDefault()}
      >
        <input
          data-testid="tenants-search"
          type="text"
          placeholder="slug or display name"
          value={search}
          onChange={(e) => handleSearchChange(e.target.value)}
          style={{
            padding: '.45rem .7rem',
            border: '1px solid #cbd5e1',
            borderRadius: '4px',
            fontSize: '.9rem',
            width: '280px',
          }}
        />
      </form>

      {listQuery.isLoading && <p>Loading...</p>}
      {listQuery.isError && (
        <p style={{ color: '#dc2626' }}>Failed to load tenants.</p>
      )}
      {data && (
        <>
          <table
            data-testid="tenants-table"
            style={{ width: '100%', borderCollapse: 'collapse', fontSize: '.9rem' }}
          >
            <thead>
              <tr style={{ background: '#f1f5f9', textAlign: 'left' }}>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Slug</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Display name</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>IDP realm</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Status</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Created</th>
                <th style={{ padding: '.5rem .75rem', borderBottom: '1px solid #e2e8f0' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {(data.items ?? []).map((row) => (
                <tr key={row.slug} data-testid={`tenant-row-${row.slug}`}>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>{row.slug}</td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>{row.display_name}</td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>{row.idp_realm_id}</td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    <span
                      data-testid={`tenant-status-${row.slug}`}
                      style={{
                        display: 'inline-block',
                        padding: '.15rem .5rem',
                        borderRadius: '999px',
                        fontSize: '.78rem',
                        fontWeight: 600,
                        background: row.status === 'ACTIVE' ? '#dcfce7' : '#f1f5f9',
                        color: row.status === 'ACTIVE' ? '#166534' : '#64748b',
                      }}
                    >
                      {row.status === 'ACTIVE' ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    {new Date(row.created_at).toLocaleDateString()}
                  </td>
                  <td style={{ padding: '.5rem .75rem', borderBottom: '1px solid #f1f5f9' }}>
                    {/* CUSTOM: row-action-navigate_edit */}
                    <button
                      type="button"
                      data-testid={`tenant-edit-${row.slug}`}
                      onClick={() => navigate(`/admin/tenants/${row.slug}/edit`)}
                      style={{
                        padding: '.3rem .65rem',
                        border: '1px solid #cbd5e1',
                        borderRadius: '4px',
                        background: '#fff',
                        cursor: 'pointer',
                        fontSize: '.82rem',
                      }}
                    >
                      Edit
                    </button>
                  </td>
                </tr>
              ))}
              {(data.items ?? []).length === 0 && (
                <tr>
                  <td colSpan={6} style={{ padding: '1rem .75rem', color: '#64748b', textAlign: 'center' }}>
                    No tenants found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>

          {total > PAGE_SIZE && (
            <div
              data-testid="tenants-pagination"
              style={{ display: 'flex', gap: '.5rem', alignItems: 'center', marginTop: '1rem' }}
            >
              <button
                type="button"
                disabled={currentPage <= 1}
                onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
                style={{
                  padding: '.3rem .65rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '4px',
                  background: '#fff',
                  cursor: currentPage <= 1 ? 'not-allowed' : 'pointer',
                  opacity: currentPage <= 1 ? 0.5 : 1,
                  fontSize: '.82rem',
                }}
              >
                Previous
              </button>
              <span style={{ fontSize: '.88rem', color: '#64748b' }}>
                Page {currentPage} of {totalPages}
              </span>
              <button
                type="button"
                disabled={currentPage >= totalPages}
                onClick={() => setOffset(offset + PAGE_SIZE)}
                style={{
                  padding: '.3rem .65rem',
                  border: '1px solid #cbd5e1',
                  borderRadius: '4px',
                  background: '#fff',
                  cursor: currentPage >= totalPages ? 'not-allowed' : 'pointer',
                  opacity: currentPage >= totalPages ? 0.5 : 1,
                  fontSize: '.82rem',
                }}
              >
                Next
              </button>
            </div>
          )}
        </>
      )}
    </div>
  )
}
